# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'SCPmRMDLJ.ui'
##
## Created by: Qt User Interface Compiler version 6.3.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDialog,
    QFrame, QGraphicsView, QGroupBox, QLabel,
    QLineEdit, QProgressBar, QPushButton, QRadioButton,
    QSizePolicy, QWidget)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(615, 481)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        #Dialog.setSizeGripEnabled(False)
        self.groupBox_3 = QGroupBox(Dialog)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(10, 10, 311, 331))
        font = QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.groupBox_3.setFont(font)
        self.graphicsView_3 = QGraphicsView(self.groupBox_3)
        self.graphicsView_3.setObjectName(u"graphicsView_3")
        self.graphicsView_3.setGeometry(QRect(10, 30, 291, 291))
        self.graphicsView_3.setFont(font)
        self.groupBox_5 = QGroupBox(Dialog)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(10, 350, 311, 111))
        self.groupBox_5.setFont(font)
        self.radioButton = QRadioButton(self.groupBox_5)
        self.radioButton.setObjectName(u"radioButton")
        self.radioButton.setGeometry(QRect(10, 40, 61, 21))
        self.radioButton.setFont(font)
        self.radioButton_2 = QRadioButton(self.groupBox_5)
        self.radioButton_2.setObjectName(u"radioButton_2")
        self.radioButton_2.setGeometry(QRect(10, 70, 71, 21))
        self.radioButton_2.setFont(font)
        self.lineEdit = QLineEdit(self.groupBox_5)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(80, 70, 41, 21))
        self.lineEdit.setFont(font)
        self.lineEdit_2 = QLineEdit(self.groupBox_5)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(80, 40, 41, 21))
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_3 = QLineEdit(self.groupBox_5)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(120, 40, 41, 21))
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_4 = QLineEdit(self.groupBox_5)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(120, 70, 41, 21))
        self.lineEdit_4.setFont(font)
        self.pushButton = QPushButton(self.groupBox_5)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(170, 50, 41, 31))
        self.pushButton.setFont(font)
        self.line_2 = QFrame(self.groupBox_5)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(210, 40, 20, 51))
        self.line_2.setFont(font)
        self.line_2.setFrameShape(QFrame.VLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.label = QLabel(self.groupBox_5)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(230, 50, 31, 21))
        self.label.setFont(font)
        self.comboBox = QComboBox(self.groupBox_5)
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(260, 50, 41, 23))
        self.comboBox.setFont(font)
        self.groupBox_6 = QGroupBox(Dialog)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(330, 10, 271, 101))
        self.groupBox_6.setFont(font)
        self.label_7 = QLabel(self.groupBox_6)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 30, 71, 20))
        self.label_7.setFont(font)
        self.label_7.setLayoutDirection(Qt.LeftToRight)
        self.label_7.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_9 = QLabel(self.groupBox_6)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(0, 50, 81, 20))
        self.label_9.setFont(font)
        self.label_9.setLayoutDirection(Qt.LeftToRight)
        self.label_9.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_10 = QLabel(self.groupBox_6)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(180, 30, 91, 20))
        font1 = QFont()
        font1.setPointSize(8)
        font1.setBold(False)
        self.label_10.setFont(font1)
        self.label_10.setLayoutDirection(Qt.LeftToRight)
        self.label_10.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_11 = QLabel(self.groupBox_6)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(90, 50, 91, 20))
        self.label_11.setFont(font1)
        self.label_11.setLayoutDirection(Qt.LeftToRight)
        self.label_11.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_12 = QLabel(self.groupBox_6)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(90, 30, 91, 20))
        self.label_12.setFont(font1)
        self.label_12.setLayoutDirection(Qt.LeftToRight)
        self.label_12.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_13 = QLabel(self.groupBox_6)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(90, 70, 41, 20))
        self.label_13.setFont(font1)
        self.label_13.setLayoutDirection(Qt.LeftToRight)
        self.label_13.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_14 = QLabel(self.groupBox_6)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(0, 70, 81, 20))
        self.label_14.setFont(font)
        self.label_14.setLayoutDirection(Qt.LeftToRight)
        self.label_14.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.groupBox_8 = QGroupBox(Dialog)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.groupBox_8.setGeometry(QRect(330, 120, 271, 221))
        self.groupBox_8.setFont(font)
        self.pushButton_15 = QPushButton(self.groupBox_8)
        self.pushButton_15.setObjectName(u"pushButton_15")
        self.pushButton_15.setGeometry(QRect(10, 60, 81, 41))
        self.pushButton_15.setFont(font)
        self.pushButton_16 = QPushButton(self.groupBox_8)
        self.pushButton_16.setObjectName(u"pushButton_16")
        self.pushButton_16.setGeometry(QRect(100, 60, 41, 41))
        self.pushButton_16.setFont(font)
        self.line_5 = QFrame(self.groupBox_8)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(150, 60, 20, 41))
        self.line_5.setFont(font)
        self.line_5.setFrameShape(QFrame.VLine)
        self.line_5.setFrameShadow(QFrame.Sunken)
        self.label_19 = QLabel(self.groupBox_8)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(170, 70, 41, 20))
        self.label_19.setFont(font)
        self.label_19.setLayoutDirection(Qt.LeftToRight)
        self.label_19.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_20 = QLabel(self.groupBox_8)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(240, 70, 21, 20))
        self.label_20.setFont(font1)
        self.label_20.setLayoutDirection(Qt.LeftToRight)
        self.label_20.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineEdit_14 = QLineEdit(self.groupBox_8)
        self.lineEdit_14.setObjectName(u"lineEdit_14")
        self.lineEdit_14.setGeometry(QRect(220, 70, 21, 21))
        self.lineEdit_14.setFont(font)
        self.label_38 = QLabel(self.groupBox_8)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(10, 30, 61, 20))
        self.label_38.setFont(font)
        self.label_38.setLayoutDirection(Qt.LeftToRight)
        self.label_38.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineEdit_16 = QLineEdit(self.groupBox_8)
        self.lineEdit_16.setObjectName(u"lineEdit_16")
        self.lineEdit_16.setGeometry(QRect(80, 30, 31, 21))
        self.lineEdit_16.setFont(font)
        self.label_39 = QLabel(self.groupBox_8)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(110, 30, 101, 20))
        self.label_39.setFont(font)
        self.label_39.setLayoutDirection(Qt.LeftToRight)
        self.label_39.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineEdit_17 = QLineEdit(self.groupBox_8)
        self.lineEdit_17.setObjectName(u"lineEdit_17")
        self.lineEdit_17.setGeometry(QRect(220, 30, 21, 21))
        self.lineEdit_17.setFont(font)
        self.label_40 = QLabel(self.groupBox_8)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(240, 30, 21, 20))
        self.label_40.setFont(font1)
        self.label_40.setLayoutDirection(Qt.LeftToRight)
        self.label_40.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.line_7 = QFrame(self.groupBox_8)
        self.line_7.setObjectName(u"line_7")
        self.line_7.setGeometry(QRect(10, 110, 251, 20))
        self.line_7.setFont(font)
        self.line_7.setFrameShape(QFrame.HLine)
        self.line_7.setFrameShadow(QFrame.Sunken)
        self.label_29 = QLabel(self.groupBox_8)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(10, 130, 71, 20))
        self.label_29.setFont(font)
        self.label_29.setLayoutDirection(Qt.LeftToRight)
        self.label_29.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_26 = QLabel(self.groupBox_8)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(90, 130, 171, 20))
        palette = QPalette()
        self.label_26.setPalette(palette)
        self.label_26.setFont(font1)
        self.label_26.setLayoutDirection(Qt.LeftToRight)
        self.label_26.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_25 = QLabel(self.groupBox_8)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(10, 150, 71, 20))
        self.label_25.setFont(font)
        self.label_25.setLayoutDirection(Qt.LeftToRight)
        self.label_25.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.progressBar = QProgressBar(self.groupBox_8)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(30, 190, 131, 20))
        self.progressBar.setFont(font)
        self.progressBar.setValue(24)
        self.label_28 = QLabel(self.groupBox_8)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(10, 170, 71, 20))
        self.label_28.setFont(font)
        self.label_28.setLayoutDirection(Qt.LeftToRight)
        self.label_28.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_27 = QLabel(self.groupBox_8)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(90, 150, 171, 20))
        self.label_27.setFont(font1)
        self.label_27.setLayoutDirection(Qt.LeftToRight)
        self.label_27.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_24 = QLabel(self.groupBox_8)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(90, 170, 61, 20))
        self.label_24.setFont(font1)
        self.label_24.setLayoutDirection(Qt.LeftToRight)
        self.label_24.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_31 = QLabel(self.groupBox_8)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(170, 190, 51, 20))
        self.label_31.setFont(font1)
        self.label_31.setLayoutDirection(Qt.LeftToRight)
        self.label_31.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.groupBox_12 = QGroupBox(Dialog)
        self.groupBox_12.setObjectName(u"groupBox_12")
        self.groupBox_12.setGeometry(QRect(330, 350, 271, 111))
        self.groupBox_12.setFont(font)
        self.checkBox_6 = QCheckBox(self.groupBox_12)
        self.checkBox_6.setObjectName(u"checkBox_6")
        self.checkBox_6.setGeometry(QRect(10, 30, 81, 21))
        self.checkBox_6.setFont(font)
        self.checkBox_7 = QCheckBox(self.groupBox_12)
        self.checkBox_7.setObjectName(u"checkBox_7")
        self.checkBox_7.setGeometry(QRect(90, 30, 131, 21))
        self.checkBox_7.setFont(font)
        self.pushButton_29 = QPushButton(self.groupBox_12)
        self.pushButton_29.setObjectName(u"pushButton_29")
        self.pushButton_29.setGeometry(QRect(10, 60, 51, 21))
        self.pushButton_29.setFont(font)
        self.lineEdit_19 = QLineEdit(self.groupBox_12)
        self.lineEdit_19.setObjectName(u"lineEdit_19")
        self.lineEdit_19.setGeometry(QRect(70, 60, 191, 21))
        self.lineEdit_19.setFont(font)
        self.label_52 = QLabel(self.groupBox_12)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setGeometry(QRect(0, 80, 61, 20))
        self.label_52.setFont(font1)
        self.label_52.setLayoutDirection(Qt.LeftToRight)
        self.label_52.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.pushButton_30 = QPushButton(self.groupBox_12)
        self.pushButton_30.setObjectName(u"pushButton_30")
        self.pushButton_30.setGeometry(QRect(220, 30, 41, 21))
        self.pushButton_30.setFont(font)
        self.lineEdit_20 = QLineEdit(self.groupBox_12)
        self.lineEdit_20.setObjectName(u"lineEdit_20")
        self.lineEdit_20.setGeometry(QRect(70, 80, 191, 21))
        self.lineEdit_20.setFont(font)

        self.retranslateUi(Dialog)

        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Slit Camera Package", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("Dialog", u"SVC", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("Dialog", u"Scaling Mode", None))
        self.radioButton.setText(QCoreApplication.translate("Dialog", u"Zscale", None))
        self.radioButton_2.setText(QCoreApplication.translate("Dialog", u"Manual", None))
        self.pushButton.setText(QCoreApplication.translate("Dialog", u"Apply", None))
        self.label.setText(QCoreApplication.translate("Dialog", u"View", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("Dialog", u"TCS Information", None))
        self.label_7.setText(QCoreApplication.translate("Dialog", u"RA / Dec :", None))
        self.label_9.setText(QCoreApplication.translate("Dialog", u"Focus :", None))
        self.label_10.setText(QCoreApplication.translate("Dialog", u"00:00:00.0", None))
        self.label_11.setText(QCoreApplication.translate("Dialog", u"0.000", None))
        self.label_12.setText(QCoreApplication.translate("Dialog", u"+00:00:00.00", None))
        self.label_13.setText(QCoreApplication.translate("Dialog", u"0.000", None))
        self.label_14.setText(QCoreApplication.translate("Dialog", u"airmass :", None))
        self.groupBox_8.setTitle(QCoreApplication.translate("Dialog", u"Image Taking Mode", None))
        self.pushButton_15.setText(QCoreApplication.translate("Dialog", u"Acquisition", None))
        self.pushButton_16.setText(QCoreApplication.translate("Dialog", u"Stop", None))
        self.label_19.setText(QCoreApplication.translate("Dialog", u"Repeat:", None))
        self.label_20.setText(QCoreApplication.translate("Dialog", u"/ 1", None))
        self.label_38.setText(QCoreApplication.translate("Dialog", u"Exp. Time:", None))
        self.label_39.setText(QCoreApplication.translate("Dialog", u"Fowler Sampling:", None))
        self.label_40.setText(QCoreApplication.translate("Dialog", u"/ 1", None))
        self.label_29.setText(QCoreApplication.translate("Dialog", u"Status :", None))
        self.label_26.setText(QCoreApplication.translate("Dialog", u"START/END/TRANSFER/DONE", None))
        self.label_25.setText(QCoreApplication.translate("Dialog", u"Start/End :", None))
        self.label_28.setText(QCoreApplication.translate("Dialog", u"Elapsed :", None))
        self.label_27.setText(QCoreApplication.translate("Dialog", u"00:00:00.0 / 00:00:00.0", None))
        self.label_24.setText(QCoreApplication.translate("Dialog", u"0.0 sec", None))
        self.label_31.setText(QCoreApplication.translate("Dialog", u"\\ 16MB", None))
        self.groupBox_12.setTitle(QCoreApplication.translate("Dialog", u"Image Storage", None))
        self.checkBox_6.setText(QCoreApplication.translate("Dialog", u"Compress", None))
        self.checkBox_7.setText(QCoreApplication.translate("Dialog", u"Automatically Save", None))
        self.pushButton_29.setText(QCoreApplication.translate("Dialog", u"Path", None))
        self.label_52.setText(QCoreApplication.translate("Dialog", u"File name", None))
        self.pushButton_30.setText(QCoreApplication.translate("Dialog", u"SAVE", None))
    # retranslateUi

