# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'macieMobLEr.ui'
##
## Created by: Qt User Interface Compiler version 6.3.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDialog, QFrame, QGroupBox,
    QLabel, QLineEdit, QListView, QPushButton,
    QRadioButton, QSizePolicy, QWidget)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(708, 343)
        self.pushButton_15 = QPushButton(Dialog)
        self.pushButton_15.setObjectName(u"pushButton_15")
        self.pushButton_15.setGeometry(QRect(10, 110, 91, 41))
        font = QFont()
        font.setPointSize(10)
        font.setBold(False)
        self.pushButton_15.setFont(font)
        self.groupBox = QGroupBox(Dialog)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 10, 151, 81))
        font1 = QFont()
        font1.setPointSize(10)
        self.groupBox.setFont(font1)
        self.pushButton_16 = QPushButton(self.groupBox)
        self.pushButton_16.setObjectName(u"pushButton_16")
        self.pushButton_16.setGeometry(QRect(10, 40, 61, 31))
        self.pushButton_16.setFont(font)
        self.pushButton_17 = QPushButton(self.groupBox)
        self.pushButton_17.setObjectName(u"pushButton_17")
        self.pushButton_17.setGeometry(QRect(80, 40, 61, 31))
        self.pushButton_17.setFont(font)
        self.groupBox_2 = QGroupBox(Dialog)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(170, 10, 251, 81))
        self.groupBox_2.setFont(font1)
        self.radioButton = QRadioButton(self.groupBox_2)
        self.radioButton.setObjectName(u"radioButton")
        self.radioButton.setGeometry(QRect(20, 40, 81, 25))
        self.radioButton.setFont(font)
        self.radioButton_2 = QRadioButton(self.groupBox_2)
        self.radioButton_2.setObjectName(u"radioButton_2")
        self.radioButton_2.setGeometry(QRect(100, 40, 81, 25))
        self.radioButton_2.setFont(font)
        self.radioButton_3 = QRadioButton(self.groupBox_2)
        self.radioButton_3.setObjectName(u"radioButton_3")
        self.radioButton_3.setGeometry(QRect(180, 40, 61, 25))
        self.radioButton_3.setFont(font)
        self.pushButton_18 = QPushButton(Dialog)
        self.pushButton_18.setObjectName(u"pushButton_18")
        self.pushButton_18.setGeometry(QRect(100, 110, 91, 41))
        self.pushButton_18.setFont(font)
        self.pushButton_19 = QPushButton(Dialog)
        self.pushButton_19.setObjectName(u"pushButton_19")
        self.pushButton_19.setGeometry(QRect(200, 110, 121, 41))
        self.pushButton_19.setFont(font)
        self.pushButton_20 = QPushButton(Dialog)
        self.pushButton_20.setObjectName(u"pushButton_20")
        self.pushButton_20.setGeometry(QRect(320, 110, 101, 41))
        self.pushButton_20.setFont(font)
        self.groupBox_3 = QGroupBox(Dialog)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(10, 170, 121, 161))
        self.groupBox_3.setFont(font1)
        self.radioButton_4 = QRadioButton(self.groupBox_3)
        self.radioButton_4.setObjectName(u"radioButton_4")
        self.radioButton_4.setGeometry(QRect(10, 100, 111, 25))
        self.radioButton_4.setFont(font)
        self.radioButton_7 = QRadioButton(self.groupBox_3)
        self.radioButton_7.setObjectName(u"radioButton_7")
        self.radioButton_7.setGeometry(QRect(10, 130, 111, 25))
        self.radioButton_7.setFont(font)
        self.radioButton_5 = QRadioButton(self.groupBox_3)
        self.radioButton_5.setObjectName(u"radioButton_5")
        self.radioButton_5.setGeometry(QRect(10, 40, 111, 25))
        self.radioButton_5.setFont(font)
        self.radioButton_6 = QRadioButton(self.groupBox_3)
        self.radioButton_6.setObjectName(u"radioButton_6")
        self.radioButton_6.setGeometry(QRect(10, 70, 111, 25))
        self.radioButton_6.setFont(font)
        self.groupBox_4 = QGroupBox(Dialog)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(140, 170, 281, 161))
        self.groupBox_4.setFont(font1)
        self.label_5 = QLabel(self.groupBox_4)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(220, 30, 51, 19))
        font2 = QFont()
        font2.setPointSize(10)
        font2.setBold(True)
        self.label_5.setFont(font2)
        self.label_4 = QLabel(self.groupBox_4)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(170, 30, 51, 19))
        self.label_4.setFont(font2)
        self.label = QLabel(self.groupBox_4)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(70, 30, 51, 19))
        self.label.setFont(font2)
        self.label_2 = QLabel(self.groupBox_4)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 30, 41, 19))
        self.label_2.setFont(font2)
        self.label_3 = QLabel(self.groupBox_4)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(120, 30, 51, 19))
        self.label_3.setFont(font2)
        self.lineEdit = QLineEdit(self.groupBox_4)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(20, 50, 41, 26))
        self.lineEdit.setFont(font1)
        self.lineEdit_2 = QLineEdit(self.groupBox_4)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(70, 50, 41, 26))
        self.lineEdit_2.setFont(font1)
        self.lineEdit_3 = QLineEdit(self.groupBox_4)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(120, 50, 41, 26))
        self.lineEdit_3.setFont(font1)
        self.lineEdit_4 = QLineEdit(self.groupBox_4)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(170, 50, 41, 26))
        self.lineEdit_4.setFont(font1)
        self.lineEdit_5 = QLineEdit(self.groupBox_4)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.lineEdit_5.setGeometry(QRect(220, 50, 41, 26))
        self.lineEdit_5.setFont(font1)
        self.label_69 = QLabel(self.groupBox_4)
        self.label_69.setObjectName(u"label_69")
        self.label_69.setGeometry(QRect(10, 90, 61, 20))
        self.label_69.setFont(font2)
        self.label_69.setLayoutDirection(Qt.LeftToRight)
        self.label_69.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_70 = QLabel(self.groupBox_4)
        self.label_70.setObjectName(u"label_70")
        self.label_70.setGeometry(QRect(120, 90, 111, 20))
        self.label_70.setFont(font2)
        self.label_70.setLayoutDirection(Qt.LeftToRight)
        self.label_70.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineEdit_29 = QLineEdit(self.groupBox_4)
        self.lineEdit_29.setObjectName(u"lineEdit_29")
        self.lineEdit_29.setGeometry(QRect(80, 90, 31, 21))
        self.lineEdit_29.setFont(font2)
        self.lineEdit_30 = QLineEdit(self.groupBox_4)
        self.lineEdit_30.setObjectName(u"lineEdit_30")
        self.lineEdit_30.setGeometry(QRect(240, 90, 21, 21))
        self.lineEdit_30.setFont(font2)
        self.pushButton_21 = QPushButton(self.groupBox_4)
        self.pushButton_21.setObjectName(u"pushButton_21")
        self.pushButton_21.setGeometry(QRect(10, 120, 81, 31))
        self.pushButton_21.setFont(font)
        self.pushButton_22 = QPushButton(self.groupBox_4)
        self.pushButton_22.setObjectName(u"pushButton_22")
        self.pushButton_22.setGeometry(QRect(100, 120, 101, 31))
        self.pushButton_22.setFont(font)
        self.pushButton_23 = QPushButton(self.groupBox_4)
        self.pushButton_23.setObjectName(u"pushButton_23")
        self.pushButton_23.setGeometry(QRect(210, 120, 61, 31))
        self.pushButton_23.setFont(font)
        self.line = QFrame(Dialog)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(420, 10, 20, 321))
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.listView = QListView(Dialog)
        self.listView.setObjectName(u"listView")
        self.listView.setGeometry(QRect(440, 10, 256, 321))

        self.retranslateUi(Dialog)

        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"MACIE", None))
        self.pushButton_15.setText(QCoreApplication.translate("Dialog", u"Initialize1", None))
        self.groupBox.setTitle(QCoreApplication.translate("Dialog", u"Power", None))
        self.pushButton_16.setText(QCoreApplication.translate("Dialog", u"On", None))
        self.pushButton_17.setText(QCoreApplication.translate("Dialog", u"Off", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("Dialog", u"Selection", None))
        self.radioButton.setText(QCoreApplication.translate("Dialog", u"H-Band", None))
        self.radioButton_2.setText(QCoreApplication.translate("Dialog", u"K-Band", None))
        self.radioButton_3.setText(QCoreApplication.translate("Dialog", u"SVC", None))
        self.pushButton_18.setText(QCoreApplication.translate("Dialog", u"Initialize2", None))
        self.pushButton_19.setText(QCoreApplication.translate("Dialog", u"DownloadMCD", None))
        self.pushButton_20.setText(QCoreApplication.translate("Dialog", u"SetDetector", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("Dialog", u"Sampling Mode", None))
        self.radioButton_4.setText(QCoreApplication.translate("Dialog", u"CDS Noise", None))
        self.radioButton_7.setText(QCoreApplication.translate("Dialog", u"Fowler", None))
        self.radioButton_5.setText(QCoreApplication.translate("Dialog", u"Up-The-Ramp", None))
        self.radioButton_6.setText(QCoreApplication.translate("Dialog", u"CDS", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("Dialog", u"Sampling Parameters", None))
        self.label_5.setText(QCoreApplication.translate("Dialog", u"Ramps", None))
        self.label_4.setText(QCoreApplication.translate("Dialog", u"Drops", None))
        self.label.setText(QCoreApplication.translate("Dialog", u"Resets", None))
        self.label_2.setText(QCoreApplication.translate("Dialog", u"Reads", None))
        self.label_3.setText(QCoreApplication.translate("Dialog", u"Groups", None))
        self.label_69.setText(QCoreApplication.translate("Dialog", u"Exp. Time:", None))
        self.label_70.setText(QCoreApplication.translate("Dialog", u"Fowler Sampling:", None))
        self.pushButton_21.setText(QCoreApplication.translate("Dialog", u"SetParam", None))
        self.pushButton_22.setText(QCoreApplication.translate("Dialog", u"AcquireRamp", None))
        self.pushButton_23.setText(QCoreApplication.translate("Dialog", u"Stop", None))
    # retranslateUi

