# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'DTPehZcfz.ui'
##
## Created by: Qt User Interface Compiler version 6.3.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QDialog, QFrame,
    QGraphicsView, QGroupBox, QLabel, QLineEdit,
    QProgressBar, QPushButton, QRadioButton, QSizePolicy,
    QWidget)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(882, 692)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.groupBox_8 = QGroupBox(Dialog)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.groupBox_8.setGeometry(QRect(330, 60, 271, 81))
        font = QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.groupBox_8.setFont(font)
        self.label_19 = QLabel(self.groupBox_8)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(150, 50, 51, 20))
        font1 = QFont()
        font1.setPointSize(8)
        font1.setBold(True)
        self.label_19.setFont(font1)
        self.label_19.setLayoutDirection(Qt.LeftToRight)
        self.label_19.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.e_repeatH = QLineEdit(self.groupBox_8)
        self.e_repeatH.setObjectName(u"e_repeatH")
        self.e_repeatH.setGeometry(QRect(210, 50, 31, 21))
        self.e_repeatH.setFont(font1)
        self.label_38 = QLabel(self.groupBox_8)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(10, 30, 61, 20))
        self.label_38.setFont(font1)
        self.label_38.setLayoutDirection(Qt.LeftToRight)
        self.label_38.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.e_exptimeH = QLineEdit(self.groupBox_8)
        self.e_exptimeH.setObjectName(u"e_exptimeH")
        self.e_exptimeH.setGeometry(QRect(80, 30, 31, 21))
        self.e_exptimeH.setFont(font1)
        self.label_39 = QLabel(self.groupBox_8)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(110, 30, 101, 20))
        self.label_39.setFont(font1)
        self.label_39.setLayoutDirection(Qt.LeftToRight)
        self.label_39.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.e_FSnumberH = QLineEdit(self.groupBox_8)
        self.e_FSnumberH.setObjectName(u"e_FSnumberH")
        self.e_FSnumberH.setGeometry(QRect(220, 30, 21, 21))
        self.e_FSnumberH.setFont(font1)
        self.label_40 = QLabel(self.groupBox_8)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(240, 30, 21, 20))
        font2 = QFont()
        font2.setPointSize(8)
        font2.setBold(False)
        self.label_40.setFont(font2)
        self.label_40.setLayoutDirection(Qt.LeftToRight)
        self.label_40.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_48 = QLabel(self.groupBox_8)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(240, 50, 21, 20))
        self.label_48.setFont(font2)
        self.label_48.setLayoutDirection(Qt.LeftToRight)
        self.label_48.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.groupBox_12 = QGroupBox(Dialog)
        self.groupBox_12.setObjectName(u"groupBox_12")
        self.groupBox_12.setGeometry(QRect(330, 550, 271, 131))
        self.groupBox_12.setFont(font)
        self.checkBox_autosave = QCheckBox(self.groupBox_12)
        self.checkBox_autosave.setObjectName(u"checkBox_autosave")
        self.checkBox_autosave.setGeometry(QRect(110, 30, 131, 21))
        self.checkBox_autosave.setFont(font1)
        self.bt_path = QPushButton(self.groupBox_12)
        self.bt_path.setObjectName(u"bt_path")
        self.bt_path.setGeometry(QRect(10, 60, 71, 21))
        self.bt_path.setFont(font1)
        self.e_path = QLineEdit(self.groupBox_12)
        self.e_path.setObjectName(u"e_path")
        self.e_path.setGeometry(QRect(90, 60, 171, 21))
        self.e_path.setFont(font1)
        self.label_52 = QLabel(self.groupBox_12)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setGeometry(QRect(0, 80, 81, 20))
        self.label_52.setFont(font2)
        self.label_52.setLayoutDirection(Qt.LeftToRight)
        self.label_52.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.bt_save = QPushButton(self.groupBox_12)
        self.bt_save.setObjectName(u"bt_save")
        self.bt_save.setGeometry(QRect(10, 30, 71, 21))
        self.bt_save.setFont(font1)
        self.e_filename_H = QLineEdit(self.groupBox_12)
        self.e_filename_H.setObjectName(u"e_filename_H")
        self.e_filename_H.setGeometry(QRect(90, 80, 171, 21))
        self.e_filename_H.setFont(font1)
        self.e_filename_K = QLineEdit(self.groupBox_12)
        self.e_filename_K.setObjectName(u"e_filename_K")
        self.e_filename_K.setGeometry(QRect(90, 100, 171, 21))
        self.e_filename_K.setFont(font1)
        self.label_53 = QLabel(self.groupBox_12)
        self.label_53.setObjectName(u"label_53")
        self.label_53.setGeometry(QRect(0, 100, 81, 20))
        self.label_53.setFont(font2)
        self.label_53.setLayoutDirection(Qt.LeftToRight)
        self.label_53.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.groupBox_3 = QGroupBox(Dialog)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(10, 10, 311, 331))
        self.groupBox_3.setFont(font)
        self.graphicsView_H = QGraphicsView(self.groupBox_3)
        self.graphicsView_H.setObjectName(u"graphicsView_H")
        self.graphicsView_H.setGeometry(QRect(10, 30, 291, 291))
        self.graphicsView_H.setFont(font1)
        self.groupBox_7 = QGroupBox(Dialog)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(10, 350, 311, 331))
        self.groupBox_7.setFont(font)
        self.graphicsView_K = QGraphicsView(self.groupBox_7)
        self.graphicsView_K.setObjectName(u"graphicsView_K")
        self.graphicsView_K.setGeometry(QRect(10, 30, 291, 291))
        self.graphicsView_K.setFont(font1)
        self.groupBox_9 = QGroupBox(Dialog)
        self.groupBox_9.setObjectName(u"groupBox_9")
        self.groupBox_9.setGeometry(QRect(330, 300, 271, 241))
        self.groupBox_9.setFont(font)
        self.label_54 = QLabel(self.groupBox_9)
        self.label_54.setObjectName(u"label_54")
        self.label_54.setGeometry(QRect(10, 40, 71, 20))
        self.label_54.setFont(font1)
        self.label_54.setLayoutDirection(Qt.LeftToRight)
        self.label_54.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_prog_sts_H = QLabel(self.groupBox_9)
        self.label_prog_sts_H.setObjectName(u"label_prog_sts_H")
        self.label_prog_sts_H.setGeometry(QRect(90, 40, 161, 20))
        palette = QPalette()
        self.label_prog_sts_H.setPalette(palette)
        self.label_prog_sts_H.setFont(font2)
        self.label_prog_sts_H.setLayoutDirection(Qt.LeftToRight)
        self.label_prog_sts_H.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_57 = QLabel(self.groupBox_9)
        self.label_57.setObjectName(u"label_57")
        self.label_57.setGeometry(QRect(10, 60, 71, 20))
        self.label_57.setFont(font1)
        self.label_57.setLayoutDirection(Qt.LeftToRight)
        self.label_57.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.progressBar_H = QProgressBar(self.groupBox_9)
        self.progressBar_H.setObjectName(u"progressBar_H")
        self.progressBar_H.setGeometry(QRect(30, 100, 131, 20))
        self.progressBar_H.setFont(font1)
        self.progressBar_H.setValue(24)
        self.label_58 = QLabel(self.groupBox_9)
        self.label_58.setObjectName(u"label_58")
        self.label_58.setGeometry(QRect(10, 80, 71, 20))
        self.label_58.setFont(font1)
        self.label_58.setLayoutDirection(Qt.LeftToRight)
        self.label_58.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_prog_time_H = QLabel(self.groupBox_9)
        self.label_prog_time_H.setObjectName(u"label_prog_time_H")
        self.label_prog_time_H.setGeometry(QRect(90, 60, 161, 20))
        self.label_prog_time_H.setFont(font2)
        self.label_prog_time_H.setLayoutDirection(Qt.LeftToRight)
        self.label_prog_time_H.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_prog_elapsed_H = QLabel(self.groupBox_9)
        self.label_prog_elapsed_H.setObjectName(u"label_prog_elapsed_H")
        self.label_prog_elapsed_H.setGeometry(QRect(90, 80, 61, 20))
        self.label_prog_elapsed_H.setFont(font2)
        self.label_prog_elapsed_H.setLayoutDirection(Qt.LeftToRight)
        self.label_prog_elapsed_H.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_61 = QLabel(self.groupBox_9)
        self.label_61.setObjectName(u"label_61")
        self.label_61.setGeometry(QRect(170, 100, 51, 20))
        self.label_61.setFont(font2)
        self.label_61.setLayoutDirection(Qt.LeftToRight)
        self.label_61.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_56 = QLabel(self.groupBox_9)
        self.label_56.setObjectName(u"label_56")
        self.label_56.setGeometry(QRect(20, 20, 71, 20))
        self.label_56.setFont(font1)
        self.label_56.setLayoutDirection(Qt.LeftToRight)
        self.label_56.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.line_7 = QFrame(self.groupBox_9)
        self.line_7.setObjectName(u"line_7")
        self.line_7.setGeometry(QRect(10, 120, 251, 20))
        self.line_7.setFont(font1)
        self.line_7.setFrameShape(QFrame.HLine)
        self.line_7.setFrameShadow(QFrame.Sunken)
        self.label_72 = QLabel(self.groupBox_9)
        self.label_72.setObjectName(u"label_72")
        self.label_72.setGeometry(QRect(20, 130, 71, 20))
        self.label_72.setFont(font1)
        self.label_72.setLayoutDirection(Qt.LeftToRight)
        self.label_72.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_73 = QLabel(self.groupBox_9)
        self.label_73.setObjectName(u"label_73")
        self.label_73.setGeometry(QRect(10, 170, 71, 20))
        self.label_73.setFont(font1)
        self.label_73.setLayoutDirection(Qt.LeftToRight)
        self.label_73.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_74 = QLabel(self.groupBox_9)
        self.label_74.setObjectName(u"label_74")
        self.label_74.setGeometry(QRect(10, 190, 71, 20))
        self.label_74.setFont(font1)
        self.label_74.setLayoutDirection(Qt.LeftToRight)
        self.label_74.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_prog_sts_K = QLabel(self.groupBox_9)
        self.label_prog_sts_K.setObjectName(u"label_prog_sts_K")
        self.label_prog_sts_K.setGeometry(QRect(90, 150, 161, 20))
        palette1 = QPalette()
        self.label_prog_sts_K.setPalette(palette1)
        self.label_prog_sts_K.setFont(font2)
        self.label_prog_sts_K.setLayoutDirection(Qt.LeftToRight)
        self.label_prog_sts_K.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_76 = QLabel(self.groupBox_9)
        self.label_76.setObjectName(u"label_76")
        self.label_76.setGeometry(QRect(170, 210, 51, 20))
        self.label_76.setFont(font2)
        self.label_76.setLayoutDirection(Qt.LeftToRight)
        self.label_76.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_77 = QLabel(self.groupBox_9)
        self.label_77.setObjectName(u"label_77")
        self.label_77.setGeometry(QRect(10, 150, 71, 20))
        self.label_77.setFont(font1)
        self.label_77.setLayoutDirection(Qt.LeftToRight)
        self.label_77.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_prog_time_K = QLabel(self.groupBox_9)
        self.label_prog_time_K.setObjectName(u"label_prog_time_K")
        self.label_prog_time_K.setGeometry(QRect(90, 170, 161, 20))
        self.label_prog_time_K.setFont(font2)
        self.label_prog_time_K.setLayoutDirection(Qt.LeftToRight)
        self.label_prog_time_K.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.progressBar_K = QProgressBar(self.groupBox_9)
        self.progressBar_K.setObjectName(u"progressBar_K")
        self.progressBar_K.setGeometry(QRect(30, 210, 131, 20))
        self.progressBar_K.setFont(font1)
        self.progressBar_K.setValue(24)
        self.label_prog_elapsed_K = QLabel(self.groupBox_9)
        self.label_prog_elapsed_K.setObjectName(u"label_prog_elapsed_K")
        self.label_prog_elapsed_K.setGeometry(QRect(90, 190, 61, 20))
        self.label_prog_elapsed_K.setFont(font2)
        self.label_prog_elapsed_K.setLayoutDirection(Qt.LeftToRight)
        self.label_prog_elapsed_K.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.radioButton_H = QRadioButton(Dialog)
        self.radioButton_H.setObjectName(u"radioButton_H")
        self.radioButton_H.setGeometry(QRect(350, 20, 81, 25))
        self.radioButton_H.setFont(font)
        self.radioButton_K = QRadioButton(Dialog)
        self.radioButton_K.setObjectName(u"radioButton_K")
        self.radioButton_K.setGeometry(QRect(440, 20, 81, 25))
        self.radioButton_K.setFont(font)
        self.radioButton_sync = QRadioButton(Dialog)
        self.radioButton_sync.setObjectName(u"radioButton_sync")
        self.radioButton_sync.setGeometry(QRect(530, 20, 61, 25))
        self.radioButton_sync.setFont(font)
        self.groupBox_10 = QGroupBox(Dialog)
        self.groupBox_10.setObjectName(u"groupBox_10")
        self.groupBox_10.setGeometry(QRect(330, 150, 271, 81))
        self.groupBox_10.setFont(font)
        self.label_69 = QLabel(self.groupBox_10)
        self.label_69.setObjectName(u"label_69")
        self.label_69.setGeometry(QRect(10, 30, 61, 20))
        self.label_69.setFont(font1)
        self.label_69.setLayoutDirection(Qt.LeftToRight)
        self.label_69.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.e_exptimeK = QLineEdit(self.groupBox_10)
        self.e_exptimeK.setObjectName(u"e_exptimeK")
        self.e_exptimeK.setGeometry(QRect(80, 30, 31, 21))
        self.e_exptimeK.setFont(font1)
        self.label_70 = QLabel(self.groupBox_10)
        self.label_70.setObjectName(u"label_70")
        self.label_70.setGeometry(QRect(110, 30, 101, 20))
        self.label_70.setFont(font1)
        self.label_70.setLayoutDirection(Qt.LeftToRight)
        self.label_70.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.e_FSnumberK = QLineEdit(self.groupBox_10)
        self.e_FSnumberK.setObjectName(u"e_FSnumberK")
        self.e_FSnumberK.setGeometry(QRect(220, 30, 21, 21))
        self.e_FSnumberK.setFont(font1)
        self.label_71 = QLabel(self.groupBox_10)
        self.label_71.setObjectName(u"label_71")
        self.label_71.setGeometry(QRect(240, 30, 21, 20))
        self.label_71.setFont(font2)
        self.label_71.setLayoutDirection(Qt.LeftToRight)
        self.label_71.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.e_repeatK = QLineEdit(self.groupBox_10)
        self.e_repeatK.setObjectName(u"e_repeatK")
        self.e_repeatK.setGeometry(QRect(210, 50, 31, 21))
        self.e_repeatK.setFont(font1)
        self.label_20 = QLabel(self.groupBox_10)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(150, 50, 51, 20))
        self.label_20.setFont(font1)
        self.label_20.setLayoutDirection(Qt.LeftToRight)
        self.label_20.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_49 = QLabel(self.groupBox_10)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setGeometry(QRect(240, 50, 21, 20))
        self.label_49.setFont(font2)
        self.label_49.setLayoutDirection(Qt.LeftToRight)
        self.label_49.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.bt_abort = QPushButton(Dialog)
        self.bt_abort.setObjectName(u"bt_abort")
        self.bt_abort.setGeometry(QRect(520, 250, 71, 41))
        self.bt_abort.setFont(font1)
        self.groupBox = QGroupBox(Dialog)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(610, 20, 261, 661))
        font3 = QFont()
        font3.setPointSize(12)
        font3.setBold(True)
        self.groupBox.setFont(font3)
        self.chk_whole = QCheckBox(self.groupBox)
        self.chk_whole.setObjectName(u"chk_whole")
        self.chk_whole.setGeometry(QRect(20, 40, 111, 31))
        self.chk_whole.setFont(font)
        self.bt_run = QPushButton(self.groupBox)
        self.bt_run.setObjectName(u"bt_run")
        self.bt_run.setGeometry(QRect(140, 40, 91, 31))
        self.bt_run.setFont(font1)
        self.groupBox_4 = QGroupBox(self.groupBox)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(10, 430, 241, 221))
        self.groupBox_4.setFont(font)
        self.bt_ltpos_set1 = QPushButton(self.groupBox_4)
        self.bt_ltpos_set1.setObjectName(u"bt_ltpos_set1")
        self.bt_ltpos_set1.setGeometry(QRect(190, 100, 41, 20))
        font4 = QFont()
        font4.setFamilies([u"Arial"])
        font4.setPointSize(8)
        font4.setBold(True)
        self.bt_ltpos_set1.setFont(font4)
        self.bt_utpos_set1 = QPushButton(self.groupBox_4)
        self.bt_utpos_set1.setObjectName(u"bt_utpos_set1")
        self.bt_utpos_set1.setGeometry(QRect(190, 40, 41, 20))
        self.bt_utpos_set1.setFont(font4)
        self.bt_utpos_set2 = QPushButton(self.groupBox_4)
        self.bt_utpos_set2.setObjectName(u"bt_utpos_set2")
        self.bt_utpos_set2.setGeometry(QRect(190, 60, 41, 20))
        self.bt_utpos_set2.setFont(font4)
        self.sts_lt_pos1_2 = QLabel(self.groupBox_4)
        self.sts_lt_pos1_2.setObjectName(u"sts_lt_pos1_2")
        self.sts_lt_pos1_2.setGeometry(QRect(120, 100, 61, 21))
        font5 = QFont()
        font5.setFamilies([u"Comic Sans MS"])
        font5.setPointSize(10)
        font5.setBold(False)
        font5.setItalic(False)
        self.sts_lt_pos1_2.setFont(font5)
        self.sts_lt_pos1_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.bt_ltpos_prev = QPushButton(self.groupBox_4)
        self.bt_ltpos_prev.setObjectName(u"bt_ltpos_prev")
        self.bt_ltpos_prev.setGeometry(QRect(16, 110, 21, 20))
        self.bt_ltpos_prev.setFont(font4)
        self.bt_ltpos_set4 = QPushButton(self.groupBox_4)
        self.bt_ltpos_set4.setObjectName(u"bt_ltpos_set4")
        self.bt_ltpos_set4.setGeometry(QRect(190, 160, 41, 20))
        self.bt_ltpos_set4.setFont(font4)
        self.bt_ltpos_set3 = QPushButton(self.groupBox_4)
        self.bt_ltpos_set3.setObjectName(u"bt_ltpos_set3")
        self.bt_ltpos_set3.setGeometry(QRect(190, 140, 41, 20))
        self.bt_ltpos_set3.setFont(font4)
        self.bt_ltpos_set2 = QPushButton(self.groupBox_4)
        self.bt_ltpos_set2.setObjectName(u"bt_ltpos_set2")
        self.bt_ltpos_set2.setGeometry(QRect(190, 120, 41, 20))
        self.bt_ltpos_set2.setFont(font4)
        self.bt_utpos_next = QPushButton(self.groupBox_4)
        self.bt_utpos_next.setObjectName(u"bt_utpos_next")
        self.bt_utpos_next.setGeometry(QRect(100, 50, 21, 20))
        self.bt_utpos_next.setFont(font4)
        self.bt_utpos_prev = QPushButton(self.groupBox_4)
        self.bt_utpos_prev.setObjectName(u"bt_utpos_prev")
        self.bt_utpos_prev.setGeometry(QRect(16, 50, 21, 20))
        self.bt_utpos_prev.setFont(font4)
        self.e_utpos = QLineEdit(self.groupBox_4)
        self.e_utpos.setObjectName(u"e_utpos")
        self.e_utpos.setGeometry(QRect(38, 50, 61, 20))
        self.e_utpos.setFont(font4)
        self.e_utpos.setLayoutDirection(Qt.LeftToRight)
        self.e_utpos.setAlignment(Qt.AlignCenter)
        self.line_2 = QFrame(self.groupBox_4)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(10, 80, 221, 20))
        self.line_2.setFont(font1)
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.e_ltpos = QLineEdit(self.groupBox_4)
        self.e_ltpos.setObjectName(u"e_ltpos")
        self.e_ltpos.setGeometry(QRect(38, 110, 61, 20))
        self.e_ltpos.setFont(font4)
        self.e_ltpos.setLayoutDirection(Qt.LeftToRight)
        self.e_ltpos.setAlignment(Qt.AlignCenter)
        self.bt_ltpos_next = QPushButton(self.groupBox_4)
        self.bt_ltpos_next.setObjectName(u"bt_ltpos_next")
        self.bt_ltpos_next.setGeometry(QRect(100, 110, 21, 20))
        self.bt_ltpos_next.setFont(font4)
        self.sts_ut_pos1_2 = QLabel(self.groupBox_4)
        self.sts_ut_pos1_2.setObjectName(u"sts_ut_pos1_2")
        self.sts_ut_pos1_2.setGeometry(QRect(120, 40, 61, 21))
        self.sts_ut_pos1_2.setFont(font5)
        self.sts_ut_pos1_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.sts_ut_pos2_2 = QLabel(self.groupBox_4)
        self.sts_ut_pos2_2.setObjectName(u"sts_ut_pos2_2")
        self.sts_ut_pos2_2.setGeometry(QRect(120, 60, 61, 21))
        self.sts_ut_pos2_2.setFont(font5)
        self.sts_ut_pos2_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.sts_lt_pos2_2 = QLabel(self.groupBox_4)
        self.sts_lt_pos2_2.setObjectName(u"sts_lt_pos2_2")
        self.sts_lt_pos2_2.setGeometry(QRect(120, 120, 61, 21))
        self.sts_lt_pos2_2.setFont(font5)
        self.sts_lt_pos2_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.sts_lt_pos3_2 = QLabel(self.groupBox_4)
        self.sts_lt_pos3_2.setObjectName(u"sts_lt_pos3_2")
        self.sts_lt_pos3_2.setGeometry(QRect(120, 140, 61, 20))
        self.sts_lt_pos3_2.setFont(font5)
        self.sts_lt_pos3_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.sts_lt_pos4_2 = QLabel(self.groupBox_4)
        self.sts_lt_pos4_2.setObjectName(u"sts_lt_pos4_2")
        self.sts_lt_pos4_2.setGeometry(QRect(120, 160, 61, 21))
        self.sts_lt_pos4_2.setFont(font5)
        self.sts_lt_pos4_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_3 = QLabel(self.groupBox_4)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 30, 120, 20))
        self.label_3.setFont(font1)
        self.label_3.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_4 = QLabel(self.groupBox_4)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 90, 120, 20))
        self.label_4.setFont(font1)
        self.label_4.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_16 = QLabel(self.groupBox_4)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(90, 190, 91, 21))
        self.label_16.setFont(font5)
        self.label_16.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.e_movinginterval = QLineEdit(self.groupBox_4)
        self.e_movinginterval.setObjectName(u"e_movinginterval")
        self.e_movinginterval.setGeometry(QRect(190, 190, 41, 20))
        self.e_movinginterval.setFont(font4)
        self.e_movinginterval.setLayoutDirection(Qt.LeftToRight)
        self.e_movinginterval.setAlignment(Qt.AlignCenter)
        self.chk_dark = QCheckBox(self.groupBox)
        self.chk_dark.setObjectName(u"chk_dark")
        self.chk_dark.setGeometry(QRect(20, 160, 111, 20))
        self.chk_dark.setFont(font1)
        self.chk_flat_on = QCheckBox(self.groupBox)
        self.chk_flat_on.setObjectName(u"chk_flat_on")
        self.chk_flat_on.setGeometry(QRect(20, 190, 111, 20))
        self.chk_flat_on.setFont(font1)
        self.chk_pinhole_ThAr = QCheckBox(self.groupBox)
        self.chk_pinhole_ThAr.setObjectName(u"chk_pinhole_ThAr")
        self.chk_pinhole_ThAr.setGeometry(QRect(20, 310, 111, 20))
        self.chk_pinhole_ThAr.setFont(font1)
        self.chk_ThAr = QCheckBox(self.groupBox)
        self.chk_ThAr.setObjectName(u"chk_ThAr")
        self.chk_ThAr.setGeometry(QRect(20, 250, 111, 20))
        self.chk_ThAr.setFont(font1)
        self.chk_flat_off = QCheckBox(self.groupBox)
        self.chk_flat_off.setObjectName(u"chk_flat_off")
        self.chk_flat_off.setGeometry(QRect(20, 220, 111, 20))
        self.chk_flat_off.setFont(font1)
        self.chk_pinhole_flat = QCheckBox(self.groupBox)
        self.chk_pinhole_flat.setObjectName(u"chk_pinhole_flat")
        self.chk_pinhole_flat.setGeometry(QRect(20, 280, 111, 20))
        self.chk_pinhole_flat.setFont(font1)
        self.chk_USAF_off = QCheckBox(self.groupBox)
        self.chk_USAF_off.setObjectName(u"chk_USAF_off")
        self.chk_USAF_off.setGeometry(QRect(20, 370, 111, 20))
        self.chk_USAF_off.setFont(font1)
        self.chk_USAF_on = QCheckBox(self.groupBox)
        self.chk_USAF_on.setObjectName(u"chk_USAF_on")
        self.chk_USAF_on.setGeometry(QRect(20, 340, 111, 20))
        self.chk_USAF_on.setFont(font1)
        self.chk_parking = QCheckBox(self.groupBox)
        self.chk_parking.setObjectName(u"chk_parking")
        self.chk_parking.setGeometry(QRect(20, 400, 111, 20))
        self.chk_parking.setFont(font1)
        self.label_67 = QLabel(self.groupBox)
        self.label_67.setObjectName(u"label_67")
        self.label_67.setGeometry(QRect(20, 110, 71, 20))
        self.label_67.setFont(font1)
        self.label_67.setLayoutDirection(Qt.LeftToRight)
        self.label_67.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_68 = QLabel(self.groupBox)
        self.label_68.setObjectName(u"label_68")
        self.label_68.setGeometry(QRect(100, 110, 81, 20))
        self.label_68.setFont(font1)
        self.label_68.setLayoutDirection(Qt.LeftToRight)
        self.label_68.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_80 = QLabel(self.groupBox)
        self.label_80.setObjectName(u"label_80")
        self.label_80.setGeometry(QRect(190, 110, 51, 20))
        self.label_80.setFont(font1)
        self.label_80.setLayoutDirection(Qt.LeftToRight)
        self.label_80.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.e_dark_exptime = QLineEdit(self.groupBox)
        self.e_dark_exptime.setObjectName(u"e_dark_exptime")
        self.e_dark_exptime.setGeometry(QRect(130, 160, 51, 21))
        self.e_dark_exptime.setFont(font1)
        self.line_3 = QFrame(self.groupBox)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(20, 140, 221, 20))
        self.line_3.setFont(font1)
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.e_flaton_exptime = QLineEdit(self.groupBox)
        self.e_flaton_exptime.setObjectName(u"e_flaton_exptime")
        self.e_flaton_exptime.setGeometry(QRect(130, 190, 51, 21))
        self.e_flaton_exptime.setFont(font1)
        self.e_flatoff_exptime = QLineEdit(self.groupBox)
        self.e_flatoff_exptime.setObjectName(u"e_flatoff_exptime")
        self.e_flatoff_exptime.setGeometry(QRect(130, 220, 51, 21))
        self.e_flatoff_exptime.setFont(font1)
        self.e_ThAr_exptime = QLineEdit(self.groupBox)
        self.e_ThAr_exptime.setObjectName(u"e_ThAr_exptime")
        self.e_ThAr_exptime.setGeometry(QRect(130, 250, 51, 21))
        self.e_ThAr_exptime.setFont(font1)
        self.e_USAFon_exptime = QLineEdit(self.groupBox)
        self.e_USAFon_exptime.setObjectName(u"e_USAFon_exptime")
        self.e_USAFon_exptime.setGeometry(QRect(130, 340, 51, 21))
        self.e_USAFon_exptime.setFont(font1)
        self.e_pinholeflat_exptime = QLineEdit(self.groupBox)
        self.e_pinholeflat_exptime.setObjectName(u"e_pinholeflat_exptime")
        self.e_pinholeflat_exptime.setGeometry(QRect(130, 280, 51, 21))
        self.e_pinholeflat_exptime.setFont(font1)
        self.e_pinholeThAr_exptime = QLineEdit(self.groupBox)
        self.e_pinholeThAr_exptime.setObjectName(u"e_pinholeThAr_exptime")
        self.e_pinholeThAr_exptime.setGeometry(QRect(130, 310, 51, 21))
        self.e_pinholeThAr_exptime.setFont(font1)
        self.e_USAFoff_exptime = QLineEdit(self.groupBox)
        self.e_USAFoff_exptime.setObjectName(u"e_USAFoff_exptime")
        self.e_USAFoff_exptime.setGeometry(QRect(130, 370, 51, 21))
        self.e_USAFoff_exptime.setFont(font1)
        self.e_parking_exptime = QLineEdit(self.groupBox)
        self.e_parking_exptime.setObjectName(u"e_parking_exptime")
        self.e_parking_exptime.setGeometry(QRect(130, 400, 51, 21))
        self.e_parking_exptime.setFont(font1)
        self.e_flaton_repeat = QLineEdit(self.groupBox)
        self.e_flaton_repeat.setObjectName(u"e_flaton_repeat")
        self.e_flaton_repeat.setGeometry(QRect(200, 190, 41, 21))
        self.e_flaton_repeat.setFont(font1)
        self.e_USAFoff_repeat = QLineEdit(self.groupBox)
        self.e_USAFoff_repeat.setObjectName(u"e_USAFoff_repeat")
        self.e_USAFoff_repeat.setGeometry(QRect(200, 370, 41, 21))
        self.e_USAFoff_repeat.setFont(font1)
        self.e_flatoff_repeat = QLineEdit(self.groupBox)
        self.e_flatoff_repeat.setObjectName(u"e_flatoff_repeat")
        self.e_flatoff_repeat.setGeometry(QRect(200, 220, 41, 21))
        self.e_flatoff_repeat.setFont(font1)
        self.e_dark_repeat = QLineEdit(self.groupBox)
        self.e_dark_repeat.setObjectName(u"e_dark_repeat")
        self.e_dark_repeat.setGeometry(QRect(200, 160, 41, 21))
        self.e_dark_repeat.setFont(font1)
        self.e_pinholeflat_repeat = QLineEdit(self.groupBox)
        self.e_pinholeflat_repeat.setObjectName(u"e_pinholeflat_repeat")
        self.e_pinholeflat_repeat.setGeometry(QRect(200, 280, 41, 21))
        self.e_pinholeflat_repeat.setFont(font1)
        self.e_pinholeThAr_repeat = QLineEdit(self.groupBox)
        self.e_pinholeThAr_repeat.setObjectName(u"e_pinholeThAr_repeat")
        self.e_pinholeThAr_repeat.setGeometry(QRect(200, 310, 41, 21))
        self.e_pinholeThAr_repeat.setFont(font1)
        self.e_parking_repeat = QLineEdit(self.groupBox)
        self.e_parking_repeat.setObjectName(u"e_parking_repeat")
        self.e_parking_repeat.setGeometry(QRect(200, 400, 41, 21))
        self.e_parking_repeat.setFont(font1)
        self.e_ThAr_repeat = QLineEdit(self.groupBox)
        self.e_ThAr_repeat.setObjectName(u"e_ThAr_repeat")
        self.e_ThAr_repeat.setGeometry(QRect(200, 250, 41, 21))
        self.e_ThAr_repeat.setFont(font1)
        self.e_USAFon_repeat = QLineEdit(self.groupBox)
        self.e_USAFon_repeat.setObjectName(u"e_USAFon_repeat")
        self.e_USAFon_repeat.setGeometry(QRect(200, 340, 41, 21))
        self.e_USAFon_repeat.setFont(font1)
        self.line_4 = QFrame(self.groupBox)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(20, 80, 221, 20))
        self.line_4.setFont(font1)
        self.line_4.setFrameShape(QFrame.HLine)
        self.line_4.setFrameShadow(QFrame.Sunken)
        self.bt_acquisition = QPushButton(Dialog)
        self.bt_acquisition.setObjectName(u"bt_acquisition")
        self.bt_acquisition.setGeometry(QRect(340, 250, 171, 41))
        self.bt_acquisition.setFont(font1)

        self.retranslateUi(Dialog)

        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Data Taking Package", None))
        self.groupBox_8.setTitle(QCoreApplication.translate("Dialog", u"H (& K) Band", None))
        self.label_19.setText(QCoreApplication.translate("Dialog", u"Repeat:", None))
        self.label_38.setText(QCoreApplication.translate("Dialog", u"Exp. Time:", None))
        self.label_39.setText(QCoreApplication.translate("Dialog", u"Fowler Sampling:", None))
        self.label_40.setText(QCoreApplication.translate("Dialog", u"/ 1", None))
        self.label_48.setText(QCoreApplication.translate("Dialog", u"/ 1", None))
        self.groupBox_12.setTitle(QCoreApplication.translate("Dialog", u"Save FITS File", None))
        self.checkBox_autosave.setText(QCoreApplication.translate("Dialog", u"Automatically Save", None))
        self.bt_path.setText(QCoreApplication.translate("Dialog", u"Path", None))
        self.label_52.setText(QCoreApplication.translate("Dialog", u"File name (H)", None))
        self.bt_save.setText(QCoreApplication.translate("Dialog", u"SAVE", None))
        self.label_53.setText(QCoreApplication.translate("Dialog", u"File name (K)", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("Dialog", u"H-Band", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("Dialog", u"K-Band", None))
        self.groupBox_9.setTitle(QCoreApplication.translate("Dialog", u"Image Taking Status", None))
        self.label_54.setText(QCoreApplication.translate("Dialog", u"Status :", None))
        self.label_prog_sts_H.setText(QCoreApplication.translate("Dialog", u"START/END/TRANSFER/DONE", None))
        self.label_57.setText(QCoreApplication.translate("Dialog", u"Start/End :", None))
        self.label_58.setText(QCoreApplication.translate("Dialog", u"Elapsed :", None))
        self.label_prog_time_H.setText(QCoreApplication.translate("Dialog", u"00:00:00.0 / 00:00:00.0", None))
        self.label_prog_elapsed_H.setText(QCoreApplication.translate("Dialog", u"0.0 sec", None))
        self.label_61.setText(QCoreApplication.translate("Dialog", u"\\ 16MB", None))
        self.label_56.setText(QCoreApplication.translate("Dialog", u"H-Band", None))
        self.label_72.setText(QCoreApplication.translate("Dialog", u"K-Band", None))
        self.label_73.setText(QCoreApplication.translate("Dialog", u"Start/End :", None))
        self.label_74.setText(QCoreApplication.translate("Dialog", u"Elapsed :", None))
        self.label_prog_sts_K.setText(QCoreApplication.translate("Dialog", u"START/END/TRANSFER/DONE", None))
        self.label_76.setText(QCoreApplication.translate("Dialog", u"\\ 16MB", None))
        self.label_77.setText(QCoreApplication.translate("Dialog", u"Status :", None))
        self.label_prog_time_K.setText(QCoreApplication.translate("Dialog", u"00:00:00.0 / 00:00:00.0", None))
        self.label_prog_elapsed_K.setText(QCoreApplication.translate("Dialog", u"0.0 sec", None))
        self.radioButton_H.setText(QCoreApplication.translate("Dialog", u"H-Band", None))
        self.radioButton_K.setText(QCoreApplication.translate("Dialog", u"K-Band", None))
        self.radioButton_sync.setText(QCoreApplication.translate("Dialog", u"Sync", None))
        self.groupBox_10.setTitle(QCoreApplication.translate("Dialog", u"K-Band", None))
        self.label_69.setText(QCoreApplication.translate("Dialog", u"Exp. Time:", None))
        self.label_70.setText(QCoreApplication.translate("Dialog", u"Fowler Sampling:", None))
        self.label_71.setText(QCoreApplication.translate("Dialog", u"/ 1", None))
        self.label_20.setText(QCoreApplication.translate("Dialog", u"Repeat:", None))
        self.label_49.setText(QCoreApplication.translate("Dialog", u"/ 1", None))
        self.bt_abort.setText(QCoreApplication.translate("Dialog", u"Abort", None))
        self.groupBox.setTitle(QCoreApplication.translate("Dialog", u"Calibration system control", None))
        self.chk_whole.setText(QCoreApplication.translate("Dialog", u"whole select", None))
        self.bt_run.setText(QCoreApplication.translate("Dialog", u"RUN", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("Dialog", u"Set motor position", None))
        self.bt_ltpos_set1.setText(QCoreApplication.translate("Dialog", u"Set", None))
        self.bt_utpos_set1.setText(QCoreApplication.translate("Dialog", u"Set", None))
        self.bt_utpos_set2.setText(QCoreApplication.translate("Dialog", u"Set", None))
        self.sts_lt_pos1_2.setText(QCoreApplication.translate("Dialog", u"     position 1", None))
        self.bt_ltpos_prev.setText(QCoreApplication.translate("Dialog", u"\u25c0", None))
        self.bt_ltpos_set4.setText(QCoreApplication.translate("Dialog", u"Set", None))
        self.bt_ltpos_set3.setText(QCoreApplication.translate("Dialog", u"Set", None))
        self.bt_ltpos_set2.setText(QCoreApplication.translate("Dialog", u"Set", None))
        self.bt_utpos_next.setText(QCoreApplication.translate("Dialog", u"\u25b6", None))
        self.bt_utpos_prev.setText(QCoreApplication.translate("Dialog", u"\u25c0", None))
        self.bt_ltpos_next.setText(QCoreApplication.translate("Dialog", u"\u25b6", None))
        self.sts_ut_pos1_2.setText(QCoreApplication.translate("Dialog", u"      position 1", None))
        self.sts_ut_pos2_2.setText(QCoreApplication.translate("Dialog", u"position 2", None))
        self.sts_lt_pos2_2.setText(QCoreApplication.translate("Dialog", u"position 2", None))
        self.sts_lt_pos3_2.setText(QCoreApplication.translate("Dialog", u"position 3", None))
        self.sts_lt_pos4_2.setText(QCoreApplication.translate("Dialog", u"position 4", None))
        self.label_3.setText(QCoreApplication.translate("Dialog", u"Upper Translator", None))
        self.label_4.setText(QCoreApplication.translate("Dialog", u"Lower Translator", None))
        self.label_16.setText(QCoreApplication.translate("Dialog", u"moving interval:", None))
        self.chk_dark.setText(QCoreApplication.translate("Dialog", u"Dark", None))
        self.chk_flat_on.setText(QCoreApplication.translate("Dialog", u"Flat ON", None))
        self.chk_pinhole_ThAr.setText(QCoreApplication.translate("Dialog", u"Pinhole-ThAr", None))
        self.chk_ThAr.setText(QCoreApplication.translate("Dialog", u"Th-Ar", None))
        self.chk_flat_off.setText(QCoreApplication.translate("Dialog", u"Flat OFF", None))
        self.chk_pinhole_flat.setText(QCoreApplication.translate("Dialog", u"Pinhole-Flat", None))
        self.chk_USAF_off.setText(QCoreApplication.translate("Dialog", u"USAP OFF", None))
        self.chk_USAF_on.setText(QCoreApplication.translate("Dialog", u"USAF ON", None))
        self.chk_parking.setText(QCoreApplication.translate("Dialog", u"PARKING", None))
        self.label_67.setText(QCoreApplication.translate("Dialog", u"Frame Type", None))
        self.label_68.setText(QCoreApplication.translate("Dialog", u"Exposure Time", None))
        self.label_80.setText(QCoreApplication.translate("Dialog", u"Repeat", None))
        self.bt_acquisition.setText(QCoreApplication.translate("Dialog", u"Acquisition", None))
    # retranslateUi

