# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'DTPWFwKVS.ui'
##
## Created by: Qt User Interface Compiler version 6.3.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QDialog, QFrame,
    QGraphicsView, QGroupBox, QLabel, QLineEdit,
    QProgressBar, QPushButton, QRadioButton, QSizePolicy,
    QWidget)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(882, 692)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.groupBox_8 = QGroupBox(Dialog)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.groupBox_8.setGeometry(QRect(330, 60, 271, 81))
        font = QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.groupBox_8.setFont(font)
        self.label_19 = QLabel(self.groupBox_8)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(150, 50, 51, 20))
        self.label_19.setFont(font)
        self.label_19.setLayoutDirection(Qt.LeftToRight)
        self.label_19.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineEdit_14 = QLineEdit(self.groupBox_8)
        self.lineEdit_14.setObjectName(u"lineEdit_14")
        self.lineEdit_14.setGeometry(QRect(210, 50, 31, 21))
        self.lineEdit_14.setFont(font)
        self.label_38 = QLabel(self.groupBox_8)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(10, 30, 61, 20))
        self.label_38.setFont(font)
        self.label_38.setLayoutDirection(Qt.LeftToRight)
        self.label_38.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineEdit_16 = QLineEdit(self.groupBox_8)
        self.lineEdit_16.setObjectName(u"lineEdit_16")
        self.lineEdit_16.setGeometry(QRect(80, 30, 31, 21))
        self.lineEdit_16.setFont(font)
        self.label_39 = QLabel(self.groupBox_8)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(110, 30, 101, 20))
        self.label_39.setFont(font)
        self.label_39.setLayoutDirection(Qt.LeftToRight)
        self.label_39.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineEdit_17 = QLineEdit(self.groupBox_8)
        self.lineEdit_17.setObjectName(u"lineEdit_17")
        self.lineEdit_17.setGeometry(QRect(220, 30, 21, 21))
        self.lineEdit_17.setFont(font)
        self.label_40 = QLabel(self.groupBox_8)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(240, 30, 21, 20))
        font1 = QFont()
        font1.setPointSize(8)
        font1.setBold(False)
        self.label_40.setFont(font1)
        self.label_40.setLayoutDirection(Qt.LeftToRight)
        self.label_40.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_48 = QLabel(self.groupBox_8)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(240, 50, 21, 20))
        self.label_48.setFont(font1)
        self.label_48.setLayoutDirection(Qt.LeftToRight)
        self.label_48.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.groupBox_12 = QGroupBox(Dialog)
        self.groupBox_12.setObjectName(u"groupBox_12")
        self.groupBox_12.setGeometry(QRect(330, 550, 271, 131))
        self.groupBox_12.setFont(font)
        self.checkBox_7 = QCheckBox(self.groupBox_12)
        self.checkBox_7.setObjectName(u"checkBox_7")
        self.checkBox_7.setGeometry(QRect(110, 30, 131, 21))
        self.checkBox_7.setFont(font)
        self.pushButton_29 = QPushButton(self.groupBox_12)
        self.pushButton_29.setObjectName(u"pushButton_29")
        self.pushButton_29.setGeometry(QRect(10, 60, 71, 21))
        self.pushButton_29.setFont(font)
        self.lineEdit_19 = QLineEdit(self.groupBox_12)
        self.lineEdit_19.setObjectName(u"lineEdit_19")
        self.lineEdit_19.setGeometry(QRect(90, 60, 171, 21))
        self.lineEdit_19.setFont(font)
        self.label_52 = QLabel(self.groupBox_12)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setGeometry(QRect(0, 80, 81, 20))
        self.label_52.setFont(font1)
        self.label_52.setLayoutDirection(Qt.LeftToRight)
        self.label_52.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.pushButton_30 = QPushButton(self.groupBox_12)
        self.pushButton_30.setObjectName(u"pushButton_30")
        self.pushButton_30.setGeometry(QRect(10, 30, 71, 21))
        self.pushButton_30.setFont(font)
        self.lineEdit_20 = QLineEdit(self.groupBox_12)
        self.lineEdit_20.setObjectName(u"lineEdit_20")
        self.lineEdit_20.setGeometry(QRect(90, 80, 171, 21))
        self.lineEdit_20.setFont(font)
        self.lineEdit_22 = QLineEdit(self.groupBox_12)
        self.lineEdit_22.setObjectName(u"lineEdit_22")
        self.lineEdit_22.setGeometry(QRect(90, 100, 171, 21))
        self.lineEdit_22.setFont(font)
        self.label_53 = QLabel(self.groupBox_12)
        self.label_53.setObjectName(u"label_53")
        self.label_53.setGeometry(QRect(0, 100, 81, 20))
        self.label_53.setFont(font1)
        self.label_53.setLayoutDirection(Qt.LeftToRight)
        self.label_53.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.groupBox_3 = QGroupBox(Dialog)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(10, 10, 311, 331))
        self.groupBox_3.setFont(font)
        self.graphicsView_3 = QGraphicsView(self.groupBox_3)
        self.graphicsView_3.setObjectName(u"graphicsView_3")
        self.graphicsView_3.setGeometry(QRect(10, 30, 291, 291))
        self.graphicsView_3.setFont(font)
        self.groupBox_7 = QGroupBox(Dialog)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(10, 350, 311, 331))
        self.groupBox_7.setFont(font)
        self.graphicsView_5 = QGraphicsView(self.groupBox_7)
        self.graphicsView_5.setObjectName(u"graphicsView_5")
        self.graphicsView_5.setGeometry(QRect(10, 30, 291, 291))
        self.graphicsView_5.setFont(font)
        self.groupBox_9 = QGroupBox(Dialog)
        self.groupBox_9.setObjectName(u"groupBox_9")
        self.groupBox_9.setGeometry(QRect(330, 300, 271, 241))
        self.groupBox_9.setFont(font)
        self.label_54 = QLabel(self.groupBox_9)
        self.label_54.setObjectName(u"label_54")
        self.label_54.setGeometry(QRect(10, 40, 71, 20))
        self.label_54.setFont(font)
        self.label_54.setLayoutDirection(Qt.LeftToRight)
        self.label_54.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_55 = QLabel(self.groupBox_9)
        self.label_55.setObjectName(u"label_55")
        self.label_55.setGeometry(QRect(90, 40, 161, 20))
        palette = QPalette()
        self.label_55.setPalette(palette)
        self.label_55.setFont(font1)
        self.label_55.setLayoutDirection(Qt.LeftToRight)
        self.label_55.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_57 = QLabel(self.groupBox_9)
        self.label_57.setObjectName(u"label_57")
        self.label_57.setGeometry(QRect(10, 60, 71, 20))
        self.label_57.setFont(font)
        self.label_57.setLayoutDirection(Qt.LeftToRight)
        self.label_57.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.progressBar_3 = QProgressBar(self.groupBox_9)
        self.progressBar_3.setObjectName(u"progressBar_3")
        self.progressBar_3.setGeometry(QRect(30, 100, 131, 20))
        self.progressBar_3.setFont(font)
        self.progressBar_3.setValue(24)
        self.label_58 = QLabel(self.groupBox_9)
        self.label_58.setObjectName(u"label_58")
        self.label_58.setGeometry(QRect(10, 80, 71, 20))
        self.label_58.setFont(font)
        self.label_58.setLayoutDirection(Qt.LeftToRight)
        self.label_58.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_59 = QLabel(self.groupBox_9)
        self.label_59.setObjectName(u"label_59")
        self.label_59.setGeometry(QRect(90, 60, 161, 20))
        self.label_59.setFont(font1)
        self.label_59.setLayoutDirection(Qt.LeftToRight)
        self.label_59.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_60 = QLabel(self.groupBox_9)
        self.label_60.setObjectName(u"label_60")
        self.label_60.setGeometry(QRect(90, 80, 61, 20))
        self.label_60.setFont(font1)
        self.label_60.setLayoutDirection(Qt.LeftToRight)
        self.label_60.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_61 = QLabel(self.groupBox_9)
        self.label_61.setObjectName(u"label_61")
        self.label_61.setGeometry(QRect(170, 100, 51, 20))
        self.label_61.setFont(font1)
        self.label_61.setLayoutDirection(Qt.LeftToRight)
        self.label_61.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_56 = QLabel(self.groupBox_9)
        self.label_56.setObjectName(u"label_56")
        self.label_56.setGeometry(QRect(20, 20, 71, 20))
        self.label_56.setFont(font)
        self.label_56.setLayoutDirection(Qt.LeftToRight)
        self.label_56.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.line_7 = QFrame(self.groupBox_9)
        self.line_7.setObjectName(u"line_7")
        self.line_7.setGeometry(QRect(10, 120, 251, 20))
        self.line_7.setFont(font)
        self.line_7.setFrameShape(QFrame.HLine)
        self.line_7.setFrameShadow(QFrame.Sunken)
        self.label_72 = QLabel(self.groupBox_9)
        self.label_72.setObjectName(u"label_72")
        self.label_72.setGeometry(QRect(20, 130, 71, 20))
        self.label_72.setFont(font)
        self.label_72.setLayoutDirection(Qt.LeftToRight)
        self.label_72.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_73 = QLabel(self.groupBox_9)
        self.label_73.setObjectName(u"label_73")
        self.label_73.setGeometry(QRect(10, 170, 71, 20))
        self.label_73.setFont(font)
        self.label_73.setLayoutDirection(Qt.LeftToRight)
        self.label_73.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_74 = QLabel(self.groupBox_9)
        self.label_74.setObjectName(u"label_74")
        self.label_74.setGeometry(QRect(10, 190, 71, 20))
        self.label_74.setFont(font)
        self.label_74.setLayoutDirection(Qt.LeftToRight)
        self.label_74.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_75 = QLabel(self.groupBox_9)
        self.label_75.setObjectName(u"label_75")
        self.label_75.setGeometry(QRect(90, 150, 161, 20))
        palette1 = QPalette()
        self.label_75.setPalette(palette1)
        self.label_75.setFont(font1)
        self.label_75.setLayoutDirection(Qt.LeftToRight)
        self.label_75.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_76 = QLabel(self.groupBox_9)
        self.label_76.setObjectName(u"label_76")
        self.label_76.setGeometry(QRect(170, 210, 51, 20))
        self.label_76.setFont(font1)
        self.label_76.setLayoutDirection(Qt.LeftToRight)
        self.label_76.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_77 = QLabel(self.groupBox_9)
        self.label_77.setObjectName(u"label_77")
        self.label_77.setGeometry(QRect(10, 150, 71, 20))
        self.label_77.setFont(font)
        self.label_77.setLayoutDirection(Qt.LeftToRight)
        self.label_77.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_78 = QLabel(self.groupBox_9)
        self.label_78.setObjectName(u"label_78")
        self.label_78.setGeometry(QRect(90, 170, 161, 20))
        self.label_78.setFont(font1)
        self.label_78.setLayoutDirection(Qt.LeftToRight)
        self.label_78.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.progressBar_4 = QProgressBar(self.groupBox_9)
        self.progressBar_4.setObjectName(u"progressBar_4")
        self.progressBar_4.setGeometry(QRect(30, 210, 131, 20))
        self.progressBar_4.setFont(font)
        self.progressBar_4.setValue(24)
        self.label_79 = QLabel(self.groupBox_9)
        self.label_79.setObjectName(u"label_79")
        self.label_79.setGeometry(QRect(90, 190, 61, 20))
        self.label_79.setFont(font1)
        self.label_79.setLayoutDirection(Qt.LeftToRight)
        self.label_79.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.radioButton = QRadioButton(Dialog)
        self.radioButton.setObjectName(u"radioButton")
        self.radioButton.setGeometry(QRect(350, 30, 81, 25))
        font2 = QFont()
        font2.setPointSize(10)
        font2.setBold(True)
        self.radioButton.setFont(font2)
        self.radioButton_2 = QRadioButton(Dialog)
        self.radioButton_2.setObjectName(u"radioButton_2")
        self.radioButton_2.setGeometry(QRect(440, 30, 81, 25))
        self.radioButton_2.setFont(font2)
        self.radioButton_3 = QRadioButton(Dialog)
        self.radioButton_3.setObjectName(u"radioButton_3")
        self.radioButton_3.setGeometry(QRect(530, 30, 61, 25))
        self.radioButton_3.setFont(font2)
        self.groupBox_10 = QGroupBox(Dialog)
        self.groupBox_10.setObjectName(u"groupBox_10")
        self.groupBox_10.setGeometry(QRect(330, 150, 271, 81))
        self.groupBox_10.setFont(font)
        self.label_69 = QLabel(self.groupBox_10)
        self.label_69.setObjectName(u"label_69")
        self.label_69.setGeometry(QRect(10, 30, 61, 20))
        self.label_69.setFont(font)
        self.label_69.setLayoutDirection(Qt.LeftToRight)
        self.label_69.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineEdit_29 = QLineEdit(self.groupBox_10)
        self.lineEdit_29.setObjectName(u"lineEdit_29")
        self.lineEdit_29.setGeometry(QRect(80, 30, 31, 21))
        self.lineEdit_29.setFont(font)
        self.label_70 = QLabel(self.groupBox_10)
        self.label_70.setObjectName(u"label_70")
        self.label_70.setGeometry(QRect(110, 30, 101, 20))
        self.label_70.setFont(font)
        self.label_70.setLayoutDirection(Qt.LeftToRight)
        self.label_70.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineEdit_30 = QLineEdit(self.groupBox_10)
        self.lineEdit_30.setObjectName(u"lineEdit_30")
        self.lineEdit_30.setGeometry(QRect(220, 30, 21, 21))
        self.lineEdit_30.setFont(font)
        self.label_71 = QLabel(self.groupBox_10)
        self.label_71.setObjectName(u"label_71")
        self.label_71.setGeometry(QRect(240, 30, 21, 20))
        self.label_71.setFont(font1)
        self.label_71.setLayoutDirection(Qt.LeftToRight)
        self.label_71.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineEdit_23 = QLineEdit(self.groupBox_10)
        self.lineEdit_23.setObjectName(u"lineEdit_23")
        self.lineEdit_23.setGeometry(QRect(210, 50, 31, 21))
        self.lineEdit_23.setFont(font)
        self.label_20 = QLabel(self.groupBox_10)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(150, 50, 51, 20))
        self.label_20.setFont(font)
        self.label_20.setLayoutDirection(Qt.LeftToRight)
        self.label_20.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_49 = QLabel(self.groupBox_10)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setGeometry(QRect(240, 50, 21, 20))
        self.label_49.setFont(font1)
        self.label_49.setLayoutDirection(Qt.LeftToRight)
        self.label_49.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.pushButton_16 = QPushButton(Dialog)
        self.pushButton_16.setObjectName(u"pushButton_16")
        self.pushButton_16.setGeometry(QRect(520, 250, 71, 41))
        self.pushButton_16.setFont(font)
        self.groupBox = QGroupBox(Dialog)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(610, 10, 261, 671))
        self.groupBox.setFont(font)
        self.chk_whole = QCheckBox(self.groupBox)
        self.chk_whole.setObjectName(u"chk_whole")
        self.chk_whole.setGeometry(QRect(20, 30, 111, 31))
        self.chk_whole.setFont(font2)
        self.bt_run = QPushButton(self.groupBox)
        self.bt_run.setObjectName(u"bt_run")
        self.bt_run.setGeometry(QRect(140, 30, 91, 31))
        self.bt_run.setFont(font)
        self.groupBox_4 = QGroupBox(self.groupBox)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(10, 390, 241, 271))
        self.groupBox_4.setFont(font)
        self.bt_ltpos_set5_2 = QPushButton(self.groupBox_4)
        self.bt_ltpos_set5_2.setObjectName(u"bt_ltpos_set5_2")
        self.bt_ltpos_set5_2.setGeometry(QRect(190, 200, 41, 20))
        font3 = QFont()
        font3.setFamilies([u"Arial"])
        font3.setPointSize(8)
        font3.setBold(True)
        self.bt_ltpos_set5_2.setFont(font3)
        self.bt_ltpos_set1_2 = QPushButton(self.groupBox_4)
        self.bt_ltpos_set1_2.setObjectName(u"bt_ltpos_set1_2")
        self.bt_ltpos_set1_2.setGeometry(QRect(190, 120, 41, 20))
        self.bt_ltpos_set1_2.setFont(font3)
        self.bt_utpos_set1_2 = QPushButton(self.groupBox_4)
        self.bt_utpos_set1_2.setObjectName(u"bt_utpos_set1_2")
        self.bt_utpos_set1_2.setGeometry(QRect(190, 40, 41, 20))
        self.bt_utpos_set1_2.setFont(font3)
        self.bt_utpos_set2_2 = QPushButton(self.groupBox_4)
        self.bt_utpos_set2_2.setObjectName(u"bt_utpos_set2_2")
        self.bt_utpos_set2_2.setGeometry(QRect(190, 60, 41, 20))
        self.bt_utpos_set2_2.setFont(font3)
        self.sts_lt_pos1_2 = QLabel(self.groupBox_4)
        self.sts_lt_pos1_2.setObjectName(u"sts_lt_pos1_2")
        self.sts_lt_pos1_2.setGeometry(QRect(120, 120, 61, 21))
        font4 = QFont()
        font4.setFamilies([u"Comic Sans MS"])
        font4.setPointSize(10)
        font4.setBold(False)
        font4.setItalic(False)
        self.sts_lt_pos1_2.setFont(font4)
        self.sts_lt_pos1_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.bt_ltpos_prev_2 = QPushButton(self.groupBox_4)
        self.bt_ltpos_prev_2.setObjectName(u"bt_ltpos_prev_2")
        self.bt_ltpos_prev_2.setGeometry(QRect(16, 130, 21, 20))
        self.bt_ltpos_prev_2.setFont(font3)
        self.bt_ltpos_set4_2 = QPushButton(self.groupBox_4)
        self.bt_ltpos_set4_2.setObjectName(u"bt_ltpos_set4_2")
        self.bt_ltpos_set4_2.setGeometry(QRect(190, 180, 41, 20))
        self.bt_ltpos_set4_2.setFont(font3)
        self.bt_ltpos_set3_2 = QPushButton(self.groupBox_4)
        self.bt_ltpos_set3_2.setObjectName(u"bt_ltpos_set3_2")
        self.bt_ltpos_set3_2.setGeometry(QRect(190, 160, 41, 20))
        self.bt_ltpos_set3_2.setFont(font3)
        self.bt_ltpos_set2_2 = QPushButton(self.groupBox_4)
        self.bt_ltpos_set2_2.setObjectName(u"bt_ltpos_set2_2")
        self.bt_ltpos_set2_2.setGeometry(QRect(190, 140, 41, 20))
        self.bt_ltpos_set2_2.setFont(font3)
        self.bt_utpos_next_2 = QPushButton(self.groupBox_4)
        self.bt_utpos_next_2.setObjectName(u"bt_utpos_next_2")
        self.bt_utpos_next_2.setGeometry(QRect(100, 50, 21, 20))
        self.bt_utpos_next_2.setFont(font3)
        self.bt_utpos_prev_2 = QPushButton(self.groupBox_4)
        self.bt_utpos_prev_2.setObjectName(u"bt_utpos_prev_2")
        self.bt_utpos_prev_2.setGeometry(QRect(16, 50, 21, 20))
        self.bt_utpos_prev_2.setFont(font3)
        self.e_utpos_2 = QLineEdit(self.groupBox_4)
        self.e_utpos_2.setObjectName(u"e_utpos_2")
        self.e_utpos_2.setGeometry(QRect(38, 50, 61, 20))
        self.e_utpos_2.setFont(font3)
        self.e_utpos_2.setLayoutDirection(Qt.LeftToRight)
        self.e_utpos_2.setAlignment(Qt.AlignCenter)
        self.line_2 = QFrame(self.groupBox_4)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(10, 90, 221, 20))
        self.line_2.setFont(font)
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.e_ltpos_2 = QLineEdit(self.groupBox_4)
        self.e_ltpos_2.setObjectName(u"e_ltpos_2")
        self.e_ltpos_2.setGeometry(QRect(38, 130, 61, 20))
        self.e_ltpos_2.setFont(font3)
        self.e_ltpos_2.setLayoutDirection(Qt.LeftToRight)
        self.e_ltpos_2.setAlignment(Qt.AlignCenter)
        self.bt_ltpos_next_2 = QPushButton(self.groupBox_4)
        self.bt_ltpos_next_2.setObjectName(u"bt_ltpos_next_2")
        self.bt_ltpos_next_2.setGeometry(QRect(100, 130, 21, 20))
        self.bt_ltpos_next_2.setFont(font3)
        self.sts_ut_pos1_2 = QLabel(self.groupBox_4)
        self.sts_ut_pos1_2.setObjectName(u"sts_ut_pos1_2")
        self.sts_ut_pos1_2.setGeometry(QRect(120, 40, 61, 21))
        self.sts_ut_pos1_2.setFont(font4)
        self.sts_ut_pos1_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.sts_ut_pos2_2 = QLabel(self.groupBox_4)
        self.sts_ut_pos2_2.setObjectName(u"sts_ut_pos2_2")
        self.sts_ut_pos2_2.setGeometry(QRect(120, 60, 61, 21))
        self.sts_ut_pos2_2.setFont(font4)
        self.sts_ut_pos2_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.sts_lt_pos2_2 = QLabel(self.groupBox_4)
        self.sts_lt_pos2_2.setObjectName(u"sts_lt_pos2_2")
        self.sts_lt_pos2_2.setGeometry(QRect(120, 140, 61, 21))
        self.sts_lt_pos2_2.setFont(font4)
        self.sts_lt_pos2_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.sts_lt_pos3_2 = QLabel(self.groupBox_4)
        self.sts_lt_pos3_2.setObjectName(u"sts_lt_pos3_2")
        self.sts_lt_pos3_2.setGeometry(QRect(120, 160, 61, 20))
        self.sts_lt_pos3_2.setFont(font4)
        self.sts_lt_pos3_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.sts_lt_pos4_2 = QLabel(self.groupBox_4)
        self.sts_lt_pos4_2.setObjectName(u"sts_lt_pos4_2")
        self.sts_lt_pos4_2.setGeometry(QRect(120, 180, 61, 21))
        self.sts_lt_pos4_2.setFont(font4)
        self.sts_lt_pos4_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.sts_lt_pos5_2 = QLabel(self.groupBox_4)
        self.sts_lt_pos5_2.setObjectName(u"sts_lt_pos5_2")
        self.sts_lt_pos5_2.setGeometry(QRect(120, 200, 61, 21))
        self.sts_lt_pos5_2.setFont(font4)
        self.sts_lt_pos5_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_3 = QLabel(self.groupBox_4)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 30, 120, 20))
        self.label_3.setFont(font)
        self.label_3.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_4 = QLabel(self.groupBox_4)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 110, 120, 20))
        self.label_4.setFont(font)
        self.label_4.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_16 = QLabel(self.groupBox_4)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(90, 230, 91, 21))
        self.label_16.setFont(font4)
        self.label_16.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.e_movinginterval_2 = QLineEdit(self.groupBox_4)
        self.e_movinginterval_2.setObjectName(u"e_movinginterval_2")
        self.e_movinginterval_2.setGeometry(QRect(190, 230, 41, 20))
        self.e_movinginterval_2.setFont(font3)
        self.e_movinginterval_2.setLayoutDirection(Qt.LeftToRight)
        self.e_movinginterval_2.setAlignment(Qt.AlignCenter)
        self.chk_whole_2 = QCheckBox(self.groupBox)
        self.chk_whole_2.setObjectName(u"chk_whole_2")
        self.chk_whole_2.setGeometry(QRect(20, 130, 111, 20))
        self.chk_whole_2.setFont(font)
        self.chk_whole_3 = QCheckBox(self.groupBox)
        self.chk_whole_3.setObjectName(u"chk_whole_3")
        self.chk_whole_3.setGeometry(QRect(20, 160, 111, 20))
        self.chk_whole_3.setFont(font)
        self.chk_whole_4 = QCheckBox(self.groupBox)
        self.chk_whole_4.setObjectName(u"chk_whole_4")
        self.chk_whole_4.setGeometry(QRect(20, 260, 111, 20))
        self.chk_whole_4.setFont(font)
        self.chk_whole_5 = QCheckBox(self.groupBox)
        self.chk_whole_5.setObjectName(u"chk_whole_5")
        self.chk_whole_5.setGeometry(QRect(20, 210, 111, 20))
        self.chk_whole_5.setFont(font)
        self.chk_whole_6 = QCheckBox(self.groupBox)
        self.chk_whole_6.setObjectName(u"chk_whole_6")
        self.chk_whole_6.setGeometry(QRect(20, 180, 111, 20))
        self.chk_whole_6.setFont(font)
        self.chk_whole_7 = QCheckBox(self.groupBox)
        self.chk_whole_7.setObjectName(u"chk_whole_7")
        self.chk_whole_7.setGeometry(QRect(20, 240, 111, 20))
        self.chk_whole_7.setFont(font)
        self.chk_whole_8 = QCheckBox(self.groupBox)
        self.chk_whole_8.setObjectName(u"chk_whole_8")
        self.chk_whole_8.setGeometry(QRect(20, 280, 111, 20))
        self.chk_whole_8.setFont(font)
        self.chk_whole_9 = QCheckBox(self.groupBox)
        self.chk_whole_9.setObjectName(u"chk_whole_9")
        self.chk_whole_9.setGeometry(QRect(20, 330, 111, 20))
        self.chk_whole_9.setFont(font)
        self.chk_whole_10 = QCheckBox(self.groupBox)
        self.chk_whole_10.setObjectName(u"chk_whole_10")
        self.chk_whole_10.setGeometry(QRect(20, 310, 111, 20))
        self.chk_whole_10.setFont(font)
        self.chk_whole_11 = QCheckBox(self.groupBox)
        self.chk_whole_11.setObjectName(u"chk_whole_11")
        self.chk_whole_11.setGeometry(QRect(20, 360, 111, 20))
        self.chk_whole_11.setFont(font)
        self.label_67 = QLabel(self.groupBox)
        self.label_67.setObjectName(u"label_67")
        self.label_67.setGeometry(QRect(20, 90, 71, 20))
        self.label_67.setFont(font)
        self.label_67.setLayoutDirection(Qt.LeftToRight)
        self.label_67.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_68 = QLabel(self.groupBox)
        self.label_68.setObjectName(u"label_68")
        self.label_68.setGeometry(QRect(100, 90, 81, 20))
        self.label_68.setFont(font)
        self.label_68.setLayoutDirection(Qt.LeftToRight)
        self.label_68.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_80 = QLabel(self.groupBox)
        self.label_80.setObjectName(u"label_80")
        self.label_80.setGeometry(QRect(190, 90, 51, 20))
        self.label_80.setFont(font)
        self.label_80.setLayoutDirection(Qt.LeftToRight)
        self.label_80.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineEdit_24 = QLineEdit(self.groupBox)
        self.lineEdit_24.setObjectName(u"lineEdit_24")
        self.lineEdit_24.setGeometry(QRect(130, 130, 51, 21))
        self.lineEdit_24.setFont(font)
        self.line_3 = QFrame(self.groupBox)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(20, 110, 221, 20))
        self.line_3.setFont(font)
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.lineEdit_28 = QLineEdit(self.groupBox)
        self.lineEdit_28.setObjectName(u"lineEdit_28")
        self.lineEdit_28.setGeometry(QRect(130, 160, 51, 21))
        self.lineEdit_28.setFont(font)
        self.lineEdit_32 = QLineEdit(self.groupBox)
        self.lineEdit_32.setObjectName(u"lineEdit_32")
        self.lineEdit_32.setGeometry(QRect(130, 180, 51, 21))
        self.lineEdit_32.setFont(font)
        self.lineEdit_33 = QLineEdit(self.groupBox)
        self.lineEdit_33.setObjectName(u"lineEdit_33")
        self.lineEdit_33.setGeometry(QRect(130, 210, 51, 21))
        self.lineEdit_33.setFont(font)
        self.lineEdit_34 = QLineEdit(self.groupBox)
        self.lineEdit_34.setObjectName(u"lineEdit_34")
        self.lineEdit_34.setGeometry(QRect(130, 310, 51, 21))
        self.lineEdit_34.setFont(font)
        self.lineEdit_35 = QLineEdit(self.groupBox)
        self.lineEdit_35.setObjectName(u"lineEdit_35")
        self.lineEdit_35.setGeometry(QRect(130, 240, 51, 21))
        self.lineEdit_35.setFont(font)
        self.lineEdit_36 = QLineEdit(self.groupBox)
        self.lineEdit_36.setObjectName(u"lineEdit_36")
        self.lineEdit_36.setGeometry(QRect(130, 260, 51, 21))
        self.lineEdit_36.setFont(font)
        self.lineEdit_37 = QLineEdit(self.groupBox)
        self.lineEdit_37.setObjectName(u"lineEdit_37")
        self.lineEdit_37.setGeometry(QRect(130, 280, 51, 21))
        self.lineEdit_37.setFont(font)
        self.lineEdit_38 = QLineEdit(self.groupBox)
        self.lineEdit_38.setObjectName(u"lineEdit_38")
        self.lineEdit_38.setGeometry(QRect(130, 330, 51, 21))
        self.lineEdit_38.setFont(font)
        self.lineEdit_39 = QLineEdit(self.groupBox)
        self.lineEdit_39.setObjectName(u"lineEdit_39")
        self.lineEdit_39.setGeometry(QRect(130, 360, 51, 21))
        self.lineEdit_39.setFont(font)
        self.lineEdit_31 = QLineEdit(self.groupBox)
        self.lineEdit_31.setObjectName(u"lineEdit_31")
        self.lineEdit_31.setGeometry(QRect(200, 160, 41, 21))
        self.lineEdit_31.setFont(font)
        self.lineEdit_40 = QLineEdit(self.groupBox)
        self.lineEdit_40.setObjectName(u"lineEdit_40")
        self.lineEdit_40.setGeometry(QRect(200, 330, 41, 21))
        self.lineEdit_40.setFont(font)
        self.lineEdit_41 = QLineEdit(self.groupBox)
        self.lineEdit_41.setObjectName(u"lineEdit_41")
        self.lineEdit_41.setGeometry(QRect(200, 280, 41, 21))
        self.lineEdit_41.setFont(font)
        self.lineEdit_42 = QLineEdit(self.groupBox)
        self.lineEdit_42.setObjectName(u"lineEdit_42")
        self.lineEdit_42.setGeometry(QRect(200, 180, 41, 21))
        self.lineEdit_42.setFont(font)
        self.lineEdit_43 = QLineEdit(self.groupBox)
        self.lineEdit_43.setObjectName(u"lineEdit_43")
        self.lineEdit_43.setGeometry(QRect(200, 130, 41, 21))
        self.lineEdit_43.setFont(font)
        self.lineEdit_44 = QLineEdit(self.groupBox)
        self.lineEdit_44.setObjectName(u"lineEdit_44")
        self.lineEdit_44.setGeometry(QRect(200, 240, 41, 21))
        self.lineEdit_44.setFont(font)
        self.lineEdit_45 = QLineEdit(self.groupBox)
        self.lineEdit_45.setObjectName(u"lineEdit_45")
        self.lineEdit_45.setGeometry(QRect(200, 260, 41, 21))
        self.lineEdit_45.setFont(font)
        self.lineEdit_46 = QLineEdit(self.groupBox)
        self.lineEdit_46.setObjectName(u"lineEdit_46")
        self.lineEdit_46.setGeometry(QRect(200, 360, 41, 21))
        self.lineEdit_46.setFont(font)
        self.lineEdit_47 = QLineEdit(self.groupBox)
        self.lineEdit_47.setObjectName(u"lineEdit_47")
        self.lineEdit_47.setGeometry(QRect(200, 210, 41, 21))
        self.lineEdit_47.setFont(font)
        self.lineEdit_48 = QLineEdit(self.groupBox)
        self.lineEdit_48.setObjectName(u"lineEdit_48")
        self.lineEdit_48.setGeometry(QRect(200, 310, 41, 21))
        self.lineEdit_48.setFont(font)
        self.line_4 = QFrame(self.groupBox)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(20, 70, 221, 20))
        self.line_4.setFont(font)
        self.line_4.setFrameShape(QFrame.HLine)
        self.line_4.setFrameShadow(QFrame.Sunken)
        self.pushButton_15 = QPushButton(Dialog)
        self.pushButton_15.setObjectName(u"pushButton_15")
        self.pushButton_15.setGeometry(QRect(340, 250, 171, 41))
        self.pushButton_15.setFont(font)

        self.retranslateUi(Dialog)

        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Data Taking Package", None))
        self.groupBox_8.setTitle(QCoreApplication.translate("Dialog", u"H (& K) Band", None))
        self.label_19.setText(QCoreApplication.translate("Dialog", u"Repeat:", None))
        self.label_38.setText(QCoreApplication.translate("Dialog", u"Exp. Time:", None))
        self.label_39.setText(QCoreApplication.translate("Dialog", u"Fowler Sampling:", None))
        self.label_40.setText(QCoreApplication.translate("Dialog", u"/ 1", None))
        self.label_48.setText(QCoreApplication.translate("Dialog", u"/ 1", None))
        self.groupBox_12.setTitle(QCoreApplication.translate("Dialog", u"Save FITS File", None))
        self.checkBox_7.setText(QCoreApplication.translate("Dialog", u"Automatically Save", None))
        self.pushButton_29.setText(QCoreApplication.translate("Dialog", u"Path", None))
        self.label_52.setText(QCoreApplication.translate("Dialog", u"File name (H)", None))
        self.pushButton_30.setText(QCoreApplication.translate("Dialog", u"SAVE", None))
        self.label_53.setText(QCoreApplication.translate("Dialog", u"File name (K)", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("Dialog", u"H-Band", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("Dialog", u"K-Band", None))
        self.groupBox_9.setTitle(QCoreApplication.translate("Dialog", u"Image Taking Status", None))
        self.label_54.setText(QCoreApplication.translate("Dialog", u"Status :", None))
        self.label_55.setText(QCoreApplication.translate("Dialog", u"START/END/TRANSFER/DONE", None))
        self.label_57.setText(QCoreApplication.translate("Dialog", u"Start/End :", None))
        self.label_58.setText(QCoreApplication.translate("Dialog", u"Elapsed :", None))
        self.label_59.setText(QCoreApplication.translate("Dialog", u"00:00:00.0 / 00:00:00.0", None))
        self.label_60.setText(QCoreApplication.translate("Dialog", u"0.0 sec", None))
        self.label_61.setText(QCoreApplication.translate("Dialog", u"\\ 16MB", None))
        self.label_56.setText(QCoreApplication.translate("Dialog", u"H-Band", None))
        self.label_72.setText(QCoreApplication.translate("Dialog", u"K-Band", None))
        self.label_73.setText(QCoreApplication.translate("Dialog", u"Start/End :", None))
        self.label_74.setText(QCoreApplication.translate("Dialog", u"Elapsed :", None))
        self.label_75.setText(QCoreApplication.translate("Dialog", u"START/END/TRANSFER/DONE", None))
        self.label_76.setText(QCoreApplication.translate("Dialog", u"\\ 16MB", None))
        self.label_77.setText(QCoreApplication.translate("Dialog", u"Status :", None))
        self.label_78.setText(QCoreApplication.translate("Dialog", u"00:00:00.0 / 00:00:00.0", None))
        self.label_79.setText(QCoreApplication.translate("Dialog", u"0.0 sec", None))
        self.radioButton.setText(QCoreApplication.translate("Dialog", u"H-Band", None))
        self.radioButton_2.setText(QCoreApplication.translate("Dialog", u"K-Band", None))
        self.radioButton_3.setText(QCoreApplication.translate("Dialog", u"Sync", None))
        self.groupBox_10.setTitle(QCoreApplication.translate("Dialog", u"K-Band", None))
        self.label_69.setText(QCoreApplication.translate("Dialog", u"Exp. Time:", None))
        self.label_70.setText(QCoreApplication.translate("Dialog", u"Fowler Sampling:", None))
        self.label_71.setText(QCoreApplication.translate("Dialog", u"/ 1", None))
        self.label_20.setText(QCoreApplication.translate("Dialog", u"Repeat:", None))
        self.label_49.setText(QCoreApplication.translate("Dialog", u"/ 1", None))
        self.pushButton_16.setText(QCoreApplication.translate("Dialog", u"Abort", None))
        self.groupBox.setTitle(QCoreApplication.translate("Dialog", u"Calibration system control", None))
        self.chk_whole.setText(QCoreApplication.translate("Dialog", u"whole select", None))
        self.bt_run.setText(QCoreApplication.translate("Dialog", u"RUN", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("Dialog", u"Set motor position", None))
        self.bt_ltpos_set5_2.setText(QCoreApplication.translate("Dialog", u"Set", None))
        self.bt_ltpos_set1_2.setText(QCoreApplication.translate("Dialog", u"Set", None))
        self.bt_utpos_set1_2.setText(QCoreApplication.translate("Dialog", u"Set", None))
        self.bt_utpos_set2_2.setText(QCoreApplication.translate("Dialog", u"Set", None))
        self.sts_lt_pos1_2.setText(QCoreApplication.translate("Dialog", u"     position 1", None))
        self.bt_ltpos_prev_2.setText(QCoreApplication.translate("Dialog", u"\u25c0", None))
        self.bt_ltpos_set4_2.setText(QCoreApplication.translate("Dialog", u"Set", None))
        self.bt_ltpos_set3_2.setText(QCoreApplication.translate("Dialog", u"Set", None))
        self.bt_ltpos_set2_2.setText(QCoreApplication.translate("Dialog", u"Set", None))
        self.bt_utpos_next_2.setText(QCoreApplication.translate("Dialog", u"\u25b6", None))
        self.bt_utpos_prev_2.setText(QCoreApplication.translate("Dialog", u"\u25c0", None))
        self.bt_ltpos_next_2.setText(QCoreApplication.translate("Dialog", u"\u25b6", None))
        self.sts_ut_pos1_2.setText(QCoreApplication.translate("Dialog", u"      position 1", None))
        self.sts_ut_pos2_2.setText(QCoreApplication.translate("Dialog", u"position 2", None))
        self.sts_lt_pos2_2.setText(QCoreApplication.translate("Dialog", u"position 2", None))
        self.sts_lt_pos3_2.setText(QCoreApplication.translate("Dialog", u"position 3", None))
        self.sts_lt_pos4_2.setText(QCoreApplication.translate("Dialog", u"position 4", None))
        self.sts_lt_pos5_2.setText(QCoreApplication.translate("Dialog", u"position 5", None))
        self.label_3.setText(QCoreApplication.translate("Dialog", u"Upper Translator", None))
        self.label_4.setText(QCoreApplication.translate("Dialog", u"Lower Translator", None))
        self.label_16.setText(QCoreApplication.translate("Dialog", u"moving interval:", None))
        self.chk_whole_2.setText(QCoreApplication.translate("Dialog", u"Dark", None))
        self.chk_whole_3.setText(QCoreApplication.translate("Dialog", u"Flat ON", None))
        self.chk_whole_4.setText(QCoreApplication.translate("Dialog", u"Pinhole-ThAr", None))
        self.chk_whole_5.setText(QCoreApplication.translate("Dialog", u"Th-Ar", None))
        self.chk_whole_6.setText(QCoreApplication.translate("Dialog", u"Flat OFF", None))
        self.chk_whole_7.setText(QCoreApplication.translate("Dialog", u"Pinhole-Flat", None))
        self.chk_whole_8.setText(QCoreApplication.translate("Dialog", u"Pinhole-ThAr", None))
        self.chk_whole_9.setText(QCoreApplication.translate("Dialog", u"USAP OFF", None))
        self.chk_whole_10.setText(QCoreApplication.translate("Dialog", u"USAF ON", None))
        self.chk_whole_11.setText(QCoreApplication.translate("Dialog", u"PARKING", None))
        self.label_67.setText(QCoreApplication.translate("Dialog", u"Frame Type", None))
        self.label_68.setText(QCoreApplication.translate("Dialog", u"Exposure Time", None))
        self.label_80.setText(QCoreApplication.translate("Dialog", u"Repeat", None))
        self.pushButton_15.setText(QCoreApplication.translate("Dialog", u"Acquisition", None))
    # retranslateUi

